### ISSUE TITLE
Import dotfile lists not recursive?

### ISSUE THREAD

**Issue by weilbith** [deadc0de6/dotdrop#112]
I started to export my profiles into separated files. Importing them in one profile and include this profile in another one does not workout and reports that nothing was to be installed for this profile.
Short example:

`config.yaml`:
```yaml
dotfiles:
  test:
    src: test
    dst: /tmp/test

profiles:
  main:
    includes:
       - sub
  sub:
    imports:
      - profiles.d/sub.yaml
```

`profiles.d/sub.yaml`:
```yaml
dotfiles:
  - test
```

Using the `import` statement directly within profile `main`, it work as expected. Same for directly installing the profile `sub`.

Btw:
Exporting probably large dotfile lists of profiles to separated file is nice. Unfortunately there remain a mass of  `<profile-name>:\nimports:\n- <path>` stubs. Do you think some approach like used for `import_variables` could work here? So that I specify a list of files, where each file is a whole profile by its own, not only the `dotfiles` section? Not sure if this can work. But would be pretty neat!
