### ISSUE TITLE
Enable profiles which are extensions of other profiles

### ISSUE THREAD

**Issue by ricpacca** [deadc0de6/dotdrop#12]
Hi, this is a feature suggestion, not an issue.
Could it be useful to have a feature where a user can define a profile as an extension of another. For example, imagine that I define a "basic" profile with the config files that I need everywhere, and then I define a "work" profile, with all the config files of basic, plus some extra ones.

Right now I would have to maintain two separate and partially duplicate lists in the config.yaml files. With such an approach the redundancy would be removed.

Thanks for the awesome program! It is so convenient!

**Comment by deadc0de6** [comment]
This is clearly doable. I was already thinking of refactoring the `profiles` part of the `config.yaml` file to include `actions` to it; therefore I could easily integrate that change in it.

Currently it is like this:
```yaml
profiles:
  host1:
  - f_vimrc
  - f_xinitrc
  host2:
  - f_vimrc
```

and was thinking of moving to something like this:
```yaml
profiles:
  host1:
      dotfiles:
        - f_xinitrc
      include:
        - host2
  host2:
      dotfiles:
        - f_vimrc
```

It would mean that profile `host1` contains all the dotfiles defined for `host2` plus `f_xinitrc`.

What do you think ?

**Comment by deadc0de6** [comment]
I have implemented the `include` in the [dev](https://github.com/deadc0de6/dotdrop/tree/dev) branch, can you test it ?

It should allow to do the above using the `include` keyword in your *config.yaml* file. See the documentation for more: [Include dotfiles from another profile](https://github.com/deadc0de6/dotdrop/tree/dev#include-dotfiles-from-another-profile).

You config file will be automatically updated to match the new format, that is from
```
profiles:
  host1:
  - ...
```
to
```
profiles:
  host1:
      dotfiles:
        - ...
```

Let me know if that matches your expectations. If your test is positive, I'll merge it in the master branch.

Thanks
