### ISSUE TITLE
Environment variable parsing

### ISSUE THREAD

**Issue by weilbith** [deadc0de6/dotdrop#120]
I have the following shorten config:
```yaml
actions:
   make_directory: "mkdir -p {0}"
dotfiles:
   test:
     actions:
        - "make_directory {{@@ env['MY_VAR'] @@}}"
     dst: '{{@@ env['MY_FOO'] @@}}/test'
     src: config/test

```

`MY_VAR` and `MY_FOO` are both defined. Unfortunately the `{{@@ env['MY_VAR'] @@}}` part gets not replaced before the actions is executed. So I end up with the statement:
```sh
-> executing "mkdir -p {{@@"
```
**But** the variable for the link `dst` is resolved and successfully used. I'm confused.
What am I doing wrong?

**Comment by deadc0de6** [comment]
Templating wasn't implemented for dotfile's actions. 
This should be done with the above commit.

```yaml
dotfiles:
  f_test:
    dst: ~/.test
    src: test
    actions:
      - "testaction \"{{@@ env['TEST_ENV'] @@}}\""
profiles:
  thor:
    dotfiles:
    - f_test
actions:
  testaction: "touch {0}"
```
