### ISSUE TITLE
[Feature Request] global actions

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#125]
For every dotfiles install I do some pre actions with my custom scripts.
This involves third party jq/yq to parse config.yaml to get dotfiles src/dst/...
but it is complicated when dynvariables/variables are used to define values in yaml.

I wonder is it hard to implement global actions and dotfile variables?
What do you think?

**Comment by deadc0de6** [comment]
You mean creating actions that are executing even if the dotfile is not installed?

**Comment by niksfirefly** [comment]
When i define global parametrized action
```
actions:
 global?:
   pre:
     setup: {{@@ dotfile_src @@}}
```
with
`dotdrop install -f`

then this global action would run before every dotfile install

It would be great to have access to dotfile.src. dotfile.dst etc. variables in config.yaml and templates.

**Comment by deadc0de6** [comment]
Regarding adding two variables when processing a dotfile (install, compare, update, etc) pointing to their source and their destination is not a problem. I'll look at it.

For what you named *global* actions is more something like *default_actions* which are actions that would be executed for each dotfile even if none are defined.

For example:
```yaml
actions:
  pre:
    pretest: echo pretest
  post:
    posttest: echo posttest
config:
  backup: true
  create: true
  dotpath: dotfiles
  default_actions:
  - pretest
  - posttest
dotfiles:
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
```

Is that what you need?
