### ISSUE TITLE
upignore doesn't apply to transformed dotfiles

### ISSUE THREAD

**Issue by laggardkernel** [deadc0de6/dotdrop#137]
I'm trying to dump the extension list of vscode when update the vscode confs. And I use the `trans_write` as a hook to run commands to dump vscode extensions.

```yaml
dynvariables:
  vscode_conf_dir: if [ {{@@ profile @@}} = Darwin ]; then echo "${HOME}/Library/Application Support/Code"; else echo "${XDG_CONFIG_HOME:-$HOME/.config}/Code"; fi

  d_vscode:
    cmpignore:
    - '*/User/globalStorage'
    - '*/User/workspaceStorage'
    dst: '{{@@ vscode_conf_dir @@}}/User'
    src: .config/vscode
    trans_write: vscode-ext-dump
    upignore:
    - '*/User/globalStorage'
    - '*/User/workspaceStorage'

trans_write:
  vscode-ext-dump: cp -R "{0}" {1} && code --list-extensions --show-versions > $HOME/.dotfiles/bootstrap/21-vscode-extensions.txt
```

It works as expected. The only problem is that, the `upignore` doesn't apply to `{1}` (the temporary folder processed after transformation). The folders `globalStorage` and `workspaceStorage` are imported after an update.

**Comment by laggardkernel** [comment]
This may not be an appropriate case using the `trans_write`, cause the extension list is not a part  of the `vscode` dotfiles yet. But `trans_write` does work for folders, not only a single file. Because the location to import dotfiles is `{1}` after transformation, the `upignore` should apply to it.

**Comment by laggardkernel** [comment]
Damnit. The `dst` is changed as the temporary folder and the `User` string doesn't match anymore. So awkward.

**Comment by laggardkernel** [comment]
It seems I get another error related to `cmpignore`. Now the `cmpignore` pattern only **apply to directory but not files**.

```yaml
  d_vscode:
    cmpignore:
    - "*extensions.txt"
    - '*/globalStorage'
    - '*/workspaceStorage'
    - '*/keybindings.json'
    dst: ~/.config/vscode
    src: .config/vscode
    upignore:
    - '*/extensions.txt'
    - '*/globalStorage'
    - '*/workspaceStorage'
```

The problem is `keybindings.json` and `extensions.txt` files are NOT ignored during comparison. But during the comparison, `globalStorage/` and `workspaceStorage/` folders are ignored as expected. Is this a bug?

```bash
❯ tree ~/.dotfiles/dotfiles/.config/vscode
/Users/laggardkernel/.dotfiles/dotfiles/.config/vscode
├── snippets
│   └── 00-default.code-snippets
├── extensions.txt
├── keybindings.json
├── locale.json
└── settings.json

1 directory, 5 files


❯ tree ~/.config/vscode -L 1
/Users/laggardkernel/.config/vscode
├── globalStorage
├── snippets
├── workspaceStorage
├── extensions.txt
├── keybindings.json
├── locale.json
└── settings.json

3 directories, 4 files

```
