### ISSUE TITLE
[Feature Request] Define multiple entries in one dotfile key

### ISSUE THREAD

**Issue by laggardkernel** [deadc0de6/dotdrop#138]
The conf files of an app may be spread at different locations. Once they are contained in just **one** dotfile key, it's much easier to update them with

```bash
dotdrop update --key keyword
```

**Comment by deadc0de6** [comment]
I would suggest to approach this from a *profile* perspective.
Let's for example consider an hypothetical app that would have following config files: `~/.config/app/config` and `~/.app.cfg`. 

I would thus import all those in a dedicated profile:
```bash
$ dotdrop import -p myapp ~/.config/app/config ~/.app.cfg
```

and would then include that profile in your own profile, something like that
```yaml
profiles:
  myapp:
    - f_config
    - f_app.cfg
  myhostname:
    - f_something
    include:
    - myapp
```

You could then update the entire profile with
```bash
$ dotdrop update --profile myapp
```
