### ISSUE TITLE
dotfile with transfomation is updated even it's unchanged according to comparison result

### ISSUE THREAD

**Issue by laggardkernel** [deadc0de6/dotdrop#139]
I'm using `gpg` to encrypt some files in my dotfiles. 

```yaml
  f_hub:
    dst: ~/.config/hub
    src: .config/hub
    trans: gpg
    trans_write: gpg

trans:
  gpg: '"$HOME/.dotfiles/bin/gpg-decrypt" "{0}" "{1}"'
  gpg-deprecated: gpg2 -q --for-your-eyes-only --no-tty -d {0} > {1}
trans_write:
  gpg: '"$HOME/.dotfiles/bin/gpg-encrypt" "{0}" "{1}"'
  gpg-deprecated: gpg2 --batch --yes -r $GPGKEY -o {1} -e {0}
```

The `trans_write` `gpg` is just a script wrapper of `gpg` encryption with additional folder support. (If `{0}` is a file, encrypt/decrypt it, if `{0}` is a folder, encrypt/decrypt files within the folder).

The problem is, even the `dotdrop compare ~/.config/hub` shows the file is unchanged. A `dotdrop update -k f_hub` still updates the file and encrypt it.

```
❯ dotdrop compare -C ~/.config/hub
        -> transforming with ""$HOME/.dotfiles/bin/gpg-decrypt" "/Users/username/.dotfiles/dotfiles/.config/hub" "/Users/username/.dotfiles/dotfiles/.config/hub.trans""

❯ dotdrop update -f -k f_hub
        -> transforming with ""$HOME/.dotfiles/bin/gpg-encrypt" "/Users/username/.config/hub" "/var/folders/5k/4_rxxpdd505ftr8j25dxd5nc0000gn/T/094e893c-4679-4c41-975e-20171b12a46e""
        -> "/Users/username/.dotfiles/dotfiles/.config/hub" updated
```

From the output, we know that 1) during comparison, `trans` is used to **decrypt** the `hub` file in the repo and compare it with the `~/.config/hub` file. 2) But during update, it seems `~/.config/hub` file is encrypted first with `trans_write`, then compared with the `hub` file from the repo? (I didn't use verbose mode, correct me if I'm wrong.)

As far as I know, multiple `gpg` encryptions on the same file result in different output. Even the output files could be decrypted back as the **same plaintext**.

So, we'd better **do the transformation on the same side** during comparison and update?
