### ISSUE TITLE
Templating doesn't work with "dotdrop update"

### ISSUE THREAD

**Issue by cshao06** [deadc0de6/dotdrop#142]
First of all, thank for the tool!

While templating is quite convenient for installing into different profiles, it doesn't work with updating a file changed locally on one machine. To me, this essentially makes the templating feature unusable. I'm wondering if you have plan to fix this issue.

**Comment by deadc0de6** [comment]
Did you check the [wiki page on updating dotfiles with templates](https://github.com/deadc0de6/dotdrop/wiki/usage#the-dotfile-uses-templating)? It provides a few solutions to workaround that.

Currently there are no solution to *revert* a jinja2 generated file and I don't plan on implementing one. But if you have any idea how to do that, let me know.

**Comment by deadc0de6** [comment]
Consider for example below template:
```yaml
{%@@ if profile == "home" @@%}
  {%@@ for i in entries @@%}
this is the loop entry {{@@ i @@}}
  {%@@ endfor @@%}
{%@@ elif profile == "office" @@%}
something else
{%@@ endif @@%}
this is the loop entry end
```

When generated with `profile=home` and the variable `entries=['a', 'b', 'c']` the result would be:
```
this is the loop entry a
this is the loop entry b
this is the loop entry c
this is the loop entry end
```
To revert this you first have to re-insert the [jinja2](http://jinja.pocoo.org) directives that weren't taken (here the part for `profile == "office"`), what isn't that difficult, but also transform back all line(s) into [jinja2](http://jinja.pocoo.org) directives. Changing the last line `this is the loop entry c` to `this is the loop entry d` would mean not only re-adding the looping directive but also updating the `entries` variable.

And this is the first example that came to my mind but it could become even more complex.
That's the reason dotdrop provides the `-P --show-patch` option as well as other means to ease that process but it will not do it all for you unfortunately.

[Jinja2](http://jinja.pocoo.org) is used in a lot of tools beside dotdrop like for example [flask](http://flask.pocoo.org/) but I don't know any tools that revert it unfortunately. It is a nice project but out-of-scope for dotdrop I think.

**Comment by cshao06** [comment]
Thanks for the quick reply. It's a bit unfortunate that this is not easy to implement. Before really trying to look for a solution with jinja2, I'd like to think about other possible solutions.

Currently, I'm putting the conflicting lines in a different file and have the main config file source/include that. For example, I put `export DOTDROP_PROFILE=home` in `~/.host_config/zshrc` and source that in `~/.zshrc`.

In my `config.yaml`, I have the following:
```
  d_host_config_home_arch:
    dst: ~/.host_config
    src: .host_config_home_arch
  d_host_config_work_arch:
    dst: ~/.host_config
    src: .host_config_work_arch

profiles:
  home-arch:
    dotfiles:
    - d_host_config_home_arch
  work-arch:
    dotfiles:
    - d_host_config_work_arch
```

This way it stores a copy of each host specific config file. When I deploy them, the corresponding `.host_config/zshrc` will be copied according to the profile and sourced in the main `~/.zshrc`.

Let me know what you think about this approach.

Then it brings up a feature request. It'd make this process easier if you have an option for `dotdrop import` to specify a custom identifier and filename in the dotfile dir.

Thanks

**Comment by davla** [comment]
Your approach is good, it's definitely the way dotdrop is meant to be used. You could attempt something with variables, but if the dotfiles are different, this is the cleanest approach.

As for the feature request, the one thing is that file names and dotfile keys (what you call identifiers) need to be unique. The feature can be implemented, but you need to be ready to see dotdrop reporting errors and refusing cooperation if the keys and file names you specify are not unique.

**Comment by deadc0de6** [comment]
Yes this is a good solution, the alternative would be to use variables:
```yaml
dotfiles:
  f_host_config:
    dst: "~/.host_config"
    src: "{{@@ host_config_path @@}}"
profiles:
  home-arch:
    dotfiles:
    - f_host_config
    variables:
      host_config_path: ".host_config_home_arch"
  work-arch:
    dotfiles:
    - f_host_config
    variables:
      host_config_path: ".host_config_work_arch"
```

If you want to change the key (what you call *identifier*) you can always do that manually by editing the `config.yaml` file. As long as the new key you choose is unique it shouldn't be an issue.
I wouldn't recommend to mess with keys and filenames but if you wish to, you're always able to do it by hand but I don't see the gain of adding such an option for the `import` command.
