### ISSUE TITLE
[feature] If no src is specified, default to dotfiles entry name

### ISSUE THREAD

**Issue by aeubanks** [deadc0de6/dotdrop#150]
I end up naming each dotfile the same as the name of the dotfiles entry. It'd be nice if you didn't specify the dotfiles entry `src`, it would default to the dotfiles entry name.

e.g.
```
dotfiles:
  foo:
    dst: ~/.foo
    src: foo
```

would be equivalent to

```
dotfiles:
  foo:
    dst: ~/.foo
```
