### ISSUE TITLE
[pattern] Append

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#151]
Either it's not a common pattern, or there's a very obvious solution and nobody needs to ask for it, but I need some of my dotfiles to be *appended* to their `dst`, rather than overwriting/linking.

The use case is my `/etc/anacrontab`, which needs a couple of entries for some custom jobs. I don't want to overwrite the predefined one, nor I want to have the whole file (predefined lines + custom lines) as my dotfile, as the predefined entries can change between different version of the OS.

So, how do I achieve this? I tried with transformations, but as `dst` is not available in any way there, I cannot simply `cat` my dotfile and `dst`. I could use something like a placeholder with templating, like this
```
here lies {{@@ _dotfile_abs_dst @@}}
... my anacron jobs ...
```
and then in the transformation replace `here lies <dst_value>` with the content `<dst_value>`, but it looks absolutely horrible

So, is there an easy way out I didn't spot?

**Comment by deadc0de6** [comment]
what about this:
```yaml
variables:
  f_test: ~/.test
  f_test_tmp: /tmp/.test
dotfiles:
  f_test:
    dst: "{{@@ f_test_tmp @@}}"
    src: test
    actions:
      - strip "{{@@ f_test @@}}"
      - append "{{@@ f_test_tmp @@}}" "{{@@ f_test @@}}"
      - rm "{{@@ f_test_tmp @@}}"
actions:
  pre:
    strip: "sed -i '/^# my pattern$/,$d' {0}"    
  post:
    append: "cat {0} >> {1}"
    rm: "rm -f {0}"
```

During installation, the `strip` action is executed which *strips* everything from the pattern `# my pattern` in the dotfile. Then the dotfile is installed in a temporary location (here `f_test_tmp` which resolves to `/tmp/.test` and the post action `append` will append its content to the final dotfile. The temporary dotfile is then removed with the `rm` action.

Obviously the dotfile in the `dotpath` should start with a unique pattern (here `# my pattern`):
```
# my pattern
this is the end
```

There are a lot of improvements that can be done:
* combine the `append` and `rm` as a single command: `cat {0} >> {1}; rm -f {0}`
* get a unique temporary file with a *dynvariables* like `mktemp`
* replace blocks within the file instead of *everything to the end*
* etc

... but you get the idea

Would something like this solve your issue?

**Comment by davla** [comment]
I didn't think of variables and actions, I was fossilized on transformations (as it feels like the most natural way of handling this). Then the situation suddenly becomes solvable. Thanks, I'll close this issue when I come up with the polished thing. Maybe we can add it to the Wiki?

Btw, I think my dotfiles are starting to make sense. You can add me to the people using dotdrop if you want to. There's not so much documentation, but it will definitely come.
- https://github.com/davla/dotfiles --> The repo actually using dotdrop
- https://github.com/davla/setup --> Where that repo is actually used

**Comment by deadc0de6** [comment]
I have added your repositories to [people using dotdrop](https://github.com/deadc0de6/dotdrop/wiki/people-using-dotdrop), thanks!

Sure we'll add it to the wiki. Just ping me when you got a more polished version.

**Comment by deadc0de6** [comment]
I have added the above solution in the wiki [here](https://github.com/deadc0de6/dotdrop/wiki/append). If you get to a more polished version, please feel free to share, I'll update the page. Thanks!

**Comment by davla** [comment]
My solution is not so much more polished than that. I just have a template for `mktemp` and one more variable for the pattern, like this:
```yaml
dynvariables:
  tmpfile: mktemp /tmp/somefile-tmp.XXX
variables:
  somefile_pattern: '# my pattern'
  somefile_final: ~/.somefile
dotfiles:
  f_somefile:
    dst: "{{@@ tmpfile @@}}"
    src: somefile
    actions:
      - strip "{{@@ somefile_pattern @@}}" "{{@@ somefile_final @@}}"
      - append "{{@@ tmpfile @@}}" "{{@@ somefile_final @@}}"
actions:
  pre:
    strip: "sed -i '/^{0}$/,$d' {1}"    
  post:
    append: "cat {0} >> {1}; rm -f {0}"
```
