### ISSUE TITLE
[bug/feature] Profile actions

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#152]
Dotdrop version: v0.28.0 (commit 73696f1, branch parsing-refactornig)
Using dotdrop: as a submodule, (actually subtree, but from your point of view it's the same)

So, in #144 we discussed about profile actions.

## Actions are run for each dotfile
One of my suggestion was that `pre` actions were to be executed *once* before the first dotfile in the profile was installed, while `post` actions should fire *once* after the last dotfile in the profile is installed. Right now, the actions are executed before/after each dotfile installation. While this might be the intended behavior, in the end it doesn't add any feature to dotdrop, as this
```yaml
actions:
  example: echo example
dotfiles:
  f_aaa:
    src: aaa
    dst: ~/.aaa
  f_bbb:
    src: bbb
    dst: ~/.bbb
profiles:
  ccc:
    dotfiles:
    - f_aaa
    - f_bbb
    actions:
    - example
```
becomes just a shorthand notation for
```yaml
actions:
  example: echo example
dotfiles:
  f_aaa:
    src: aaa
    dst: ~/.aaa
    actions:
    - example
  f_bbb:
    src: bbb
    dst: ~/.bbb
    actions:
    - example
profiles:
  ccc:
    dotfiles:
    - f_aaa
    - f_bbb
```

## Actions are not imported with `include`
This we didn't talk about as we didn't think of it, but when profile `a`  `include`s profile `b`, then `b`'s profile actions should be executed as well. It doesn't really matter if they are executed before/after `b`'s dotfiles are installed or before/after `a`'s ones are, but the `b` actions should be executed. For the sake of clarity, with the following `config.yaml`
```yaml
actions:
  a-action: echo From a
  b-action: echo From b
dotfiles:
  f_aaa:
    src: aaa
    dst: ~/.aaa
  f_bbb:
    src: bbb
    dst: ~/.bbb
profiles:
  a:
    dotfiles:
    - f_aaa
    include:
    - b
    actions:
    - a-action
  b:
    dotfiles:
    - f_bbb
    actions:
    - b-action
```
the command:
```bash
dotdrop.sh -c config.yaml install -p a
```
should also execute action `b-action`.
