### ISSUE TITLE
[feature] Custom installation command

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#153]
This is a major feature, not to be implemented soon, if ever to be implemented at all. But there's not shame in asking :smile: As you can imagine, if you think it's a nice idea, I'm willing to contribute to make this happen.

So, the idea is to provide a custom command for installing dotfiles, which defaults to the bare copy we have now. Something like
```yaml
dotfiles:
  f_copied:
    src: copied
    dst: ~/.copied
  f_crontab:
    src: crontab
    install: crontab {0}
  f_appended:
    src: anacrontab
    dst: /etc/anacrontab
    install: cat {0} >> {1}
```
- The dotfile `f_crontab` has no `dst` (this might create problems though), because there's simply nowhere for it to be copied: it should in fact be installed via the `crontab` command, rather than simply copied somewhere.
- The dotfile `f_appended` is not copied anywhere, but rather the file in dotpath is appended to the one in the filesystem, by the simple command specified in the `install` key.

## Rationale
I needed to install a crontab in my dotfiles. Here it is where I ended up:
```yaml
actions:
  crontab: crontab '{0}'; rm -f '{0}'
dotfiles:
  f_crontab:
    src: anacron/crontab
    dst: '{{@@ tmp_dst @@}}'
    actions:
    - crontab  '{{@@ tmp_dst @@}}'
dynvariables:
  tmp_dst: mktemp /tmp/cron-tmp.XXX
```
This is rather convoluted and it has quite some boilerplate. It needs to use variables, temporary files and manual cleanup. And in general it's a lot of code. Just because dotdrop *needs* to copy/link things somewhere.

Also, #151 is an example of how complex and verbose can it be to do something different than copying/linking.

## Alternatives
While I was writing this, I came up with an alternative:
```yaml
actions:
  crontab: crontab {0}
  append: cat {0} >> /etc/anacrontab
dotfiles:
  f_copied:
    src: copied
    dst: ~/.copied
  f_crontab:
    src: crontab
    dst: TMP
    actions:
    - crontab
  f_appended:
    src: anacrontab
    dst: TMP
    actions:
    - append
```
So, I still prefer the previous one, but this one is more feasible, I think (even though it still sufers problems with `dst`). The special `TMP` keyword just means that the dotfile will be copied in a temporary location, which is passed as the first argument to actions, and automatically cleaned up after action execution.

This encodes the pattern I ended up with both for crontab and appending:
- Copy to a temporary file
- Do something with the temporary file
- Clean up the temporary file

So, what I'm suggesting is to support this pattern in dotdrop, rather than making the user encode it each time.

**Comment by deadc0de6** [comment]
Dotdrop is a dotfile manager and thus takes care of copying/linking files to a destination. IMHO adding specific commands  beside the basic copying/linking tend to transform it into some kind of deployment solution, for which more appropriate tools exist ([ansible](https://www.ansible.com), [salt](https://www.saltstack.com), etc).
Moreover what you are trying to do can already be done with existing features of dotdrop (as you've shown above).

For the above reason, I'm not convinced adding more custom install commands would add much beside rendering the code base much more complex for something that can already be done today.

Still I think we can find a common ground here to *simplify* this kind of deployment. What about adding dotfile specific variables available to the config as it is for the [templating](https://github.com/deadc0de6/dotdrop/wiki/templating#dotfile-variables)?

For example adding `_dotfile_abs_dst` which mirrors the dotfile `dst` path:
```yaml
actions:
  crontab: crontab {0}
  append: cat {0} >> /etc/anacrontab
dotfiles:
  f_crontab:
    src: crontab
    dst: '{{@@ tmpfile @@}}'
    actions:
    - crontab '{{@@ _dotfile_abs_dst @@}}'
  f_appended:
    src: anacrontab
    dst: '{{@@ tmpfile @@}}'
    actions:
    - append '{{@@ _dotfile_abs_dst @@}}'
dynvariables:
  tmpfile: mktemp /tmp/dotdrop-tmp
```

or even provide those variables to the actions themselves, for example:
```yaml
actions:
  crontab: crontab '{{@@ _dotfile_abs_dst @@}}'
  append: cat '{{@@ _dotfile_abs_dst @@}}' >> /etc/anacrontab
dotfiles:
  f_crontab:
    src: crontab
    dst: '{{@@ tmpfile @@}}'
    actions:
    - crontab
  f_appended:
    src: anacrontab
    dst: '{{@@ tmpfile @@}}'
    actions:
    - append
dynvariables:
  tmpfile: mktemp /tmp/dotdrop-tmp
```
But this would render those actions unavailable for use in profiles and thus make actions more difficult to handle internally.

But in the end IMHO it is just workarounds and shortcuts for things that are already working today. I have the feeling you're trying to *clean up* your config file. But since now we can import other config files, you could simply split those different elements to keep your main config clean.

main config
```yaml
config:
  import_actions:
  - actions-config.yaml
  import_variables:
  - variables-config.yaml
dotfiles:
  f_crontab:
    src: crontab
    dst: '{{@@ tmpfile @@}}'
    actions:
    - crontab '{{@@ tmpfile @@}}'
  f_anacron:
    src: anacrontab
    dst: '{{@@ tmpfile @@}}'
    actions:
    - anacron '{{@@ tmpfile @@}}'
```

`actions-config.yaml`
```yaml
actions:
  crontab: crontab {0}
  anacron: cat {0} >> /etc/anacrontab
```

`variables-config.yaml`
```yaml
dynvariables:
  tmpfile: mktemp /tmp/.dotdrop-tmp
```
