### ISSUE TITLE
[bug] Symlinking errors are not reported

### ISSUE THREAD

**Issue by aeubanks** [deadc0de6/dotdrop#154]
Dotdrop version (and git commit if run from source): v0.28.0

If a file doesn't exist and dotdrop tries to symlink it, errors are not reported.

```yaml
config:                                                                                                                                                                                                                                 
    dotpath: .                                                                                                                                                                                                                          
    showdiff: true                                                                                                                                                                                                                      
    link_dotfile_default: link                                                                                                                                                                                                          
                                                                                                                                                                                                                                        
dotfiles:                                                                                                                                                                                                                               
    aliases:                                                                                                                                                                                                                            
        dst: ~/.aliases                                                                                                                                                                                                                 
        src: aliases

profiles:
    user:
        dotfiles:
            - aliases
```

I'm pretty sure it's because `inst.link()` returns a tuple but it's not unpacked:
https://github.com/deadc0de6/dotdrop/blob/80428e669a6e87dfc3be21e90c009a0e0381d4ca/dotdrop/dotdrop.py#L113
