### ISSUE TITLE
[bug] link_children copies unwanted directories to dotfiles

### ISSUE THREAD

**Issue by mathsaey** [deadc0de6/dotdrop#159]
Dotdrop version (and git commit if run from source): v0.28.0 (37bcf665f891f0b8d973d7736abeadf65728e145)
Using dotdrop: as a submodule

I'm using dotdrop to manage my vim config, as described in the [documentation of link_children](https://github.com/deadc0de6/dotdrop/wiki/symlinked-dotfiles#link-children).
However, when I attempt to update my vim config dotdrop will always copy non-symlinked directories back into my dotfiles. New directories in the dotfiles directory get deleted.

My config (the `vim` entry should suffice but I added all the relevant bits just in case):

```
config:
  dotpath: ~/.dotfiles

...

dotfiles:
  vim:
    src: vim
    dst: ~/.vim/
    link: link_children
    actions:
      - vim_download_plug
      - vim_install_plugins

...

actions:
  vim_download_plug: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim_install_plugins: vim +PlugInstall +qall now
```

The output of `dotdrop update -d ~/.vim` (redacted the home directory of the paths):

```
[DRY] would cp -r ~/.vim/autoload ~/.dotfiles/vim/autoload
[DRY] would cp -r ~/.vim/bundle ~/.dotfiles/vim/bundle
[DRY] would rm -r ~/.dotfiles/vim/snips
```

I'd expect the opposite behaviour: dotdrop should ignore the `autoload` and `bundle` directories and offer to symlink the `~/.dotfiles/vim/snips` directory to `~/.vim`.

It is very likely that I am doing something incredibly wrong, but since this is pretty much a verbatim copy from the wiki I guess I might have run into a bug :).
