### ISSUE TITLE
[bug] global cmpignore becomes invalid in 0.29

### ISSUE THREAD

**Issue by laggardkernel** [deadc0de6/dotdrop#161]
Dotdrop version (and git commit if run from source): v0.29.1
Using dotdrop: as a submodule

**Describe the bug**

After upgrading to 0.29, the global `cmpignore` doesn't take effect anymore. 

```yaml
config:
  backup: true
  banner: false
  cmpignore:
  - '*/.DS_Store'
# omitted
```

The `.DS_Store` files are still listed in the comparison result of `dotdrop compare`.

```
...
=> compare d_ranger: diffing with "/Users/username/.config/ranger"
=> ".DS_Store" does not exist in dotdrop
...
```
