### ISSUE TITLE
[bug] Incorrect detection of link option in transformation

### ISSUE THREAD

**Issue by laggardkernel** [deadc0de6/dotdrop#170]
Dotdrop version (and git commit if run from source): v0.29.3 commit 7ca156a
Using dotdrop: as a submodule

**Describe the bug**

```
[WARN] [d_ssh] transformations disabled because dotfile is linked
```

Warning about `link`ed popped up, although the dotfile is not linked at all.

I only set global behavior as `nolink`, no link option is set for the specific dotfile `d_ssh`.

```yaml
config:
  backup: true
  banner: false
  cmpignore:
  - '*/.DS_Store'
  create: true
  dotpath: dotfiles
  ignoreempty: false
  import_actions:
  - config.d/actions.yaml
  import_variables:
  - config.d/vars.yaml
  keepdot: true
  link_dotfile_default: nolink
  link_on_import: nolink
 # ...
```
