### ISSUE TITLE
[bug] dynvariables are broken in 0.29

### ISSUE THREAD

**Issue by laggardkernel** [deadc0de6/dotdrop#177]
dotdrop version: v0.29 229a779

I use `dynvariables` to define `dst` path dynamically according to current profile name. The `dotdrop compare` doesn't work with it now.

```yaml
# config.d/vars.yaml
dynvariables:
  vscode_conf_dir: if [ "{{@@ profile @@}}" == Darwin ]; then echo "~/Library/Application Support/Code"; else echo "${XDG_CONFIG_HOME:-$HOME/.config}/Code"; fi
```

```yaml
# config.yaml
config:
  backup: true
  banner: false
  cmpignore:
  - '*/.DS_Store'
  create: true
  dotpath: dotfiles
  ignoreempty: false
  import_actions:
  - config.d/actions.yaml
  import_variables:
  - config.d/vars.yaml

...

  d_vscode:
    cmpignore:
    - '*/extensions.txt'
    - '*/globalStorage'
    - '*/workspaceStorage'
    dst: '{{@@ vscode_conf_dir @@}}/User'
    src: .config/vscode
    upignore:
    - '*/globalStorage'
    - '*/workspaceStorage'
```

Related logs.

```
[DEBUG][dotdrop.utils.shell] shell exec: if [ "" == Darwin ]; then echo "${HOME}/Library/Application Support/Code"; else echo "${XDG_CONFIG_HOME:-$HOME/.config}/Code"; fi
[DEBUG][dotdrop.utils.shell] shell result (0): /Users/username/.config/Code
```

In 0.29, the template variable `{{@@ profile @@}}` is not expanded.
