### ISSUE TITLE
[bug] `install` show diffs against template files

### ISSUE THREAD

**Issue by Maelan** [deadc0de6/dotdrop#182]
Dotdrop version: v0.29.1 (commit 9181405)

**Describe the bug**

The `install` operation with the option `showdiff: true` prints the differences between the template files and the installed files, instead of showing the differences between the preprocessed files and the installed files.

**Steps to Reproduce**

 1. Relevant part of `config.yaml`:
    
    ```yaml
    config:
      showdiff: true
    variables:
      BEFORE_JINJA: after jinja
    dotfiles:
      test:
        dst: ~/test
        src: test
    ```

 1. Create a dotfile named `test` with the following contents:
    
        {{@@ BEFORE_JINJA @@}}
    
    Also create `~/test` with the following contents:
    
        after jinja
        this is the installed file

 1. Run `./dotdrop.sh install test`

**Expected behavior**

The `install` operation should show the same diff as the `compare` operation.

**Additional information**

Wrong output:

```diff
$ ./dotdrop.sh install test

diff "/home/me/dotfiles/dotfiles/test" VS "/home/me/test"
1c1,2
< {{@@ BEFORE_JINJA @@}}
---
> after jinja
> this is the installed file
Overwrite "/home/me/test" [y/N] ?
```

Right output:

```diff
$ ./dotdrop.sh compare -C ~/test

=> compare test: diffing with "/home/me/test"
1a2
> this is the installed file
```
