### ISSUE TITLE
[help] Is there a way to set umask for dotdrop?

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#186]
Is there a way to set umask for dotdrop?
I have accounts with different umask and dotdrop always use user umask
for example with umask 0002
 ~/.ssh/config file gets 644 permissions
so ssh is not working with 

> Bad owner or permissions error

So far i tried pre/post actions with
- chmod
- umask
and nothing works
regards

**Comment by deadc0de6** [comment]
Here's what I tried and it worked:
```yaml
actions:
  post:
    chmod: "chmod 777 {{@@ _dotfile_abs_dst @@}}"
dotfiles:
  f_test:
    dst: ~/.test
    src: test
    actions:
      - chmod
```

What wasn't working?
