### ISSUE TITLE
[feature] conditional dotfiles import?

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#187]
I use templating functions in config.yaml
`if exists(file.yaml) - else default.yaml - condition`
for import dotfiles for profile when specific file exist.

So for example if NOT exist file
profile_user_uid.yaml based on dynvariable user
then 
profile_default.yaml 
is loaded.

Is it ok? Is there any other simpler solution?

**Comment by deadc0de6** [comment]
Hm templating won't work in the `config.yaml` file as it does in templates. You could however use a combination of variables and dynvariables.

For example (untested):

```yaml
dynvariables:
  user: "echo $USER"
  config_file: test -f "{{@@ user_config @@}}" && echo "{{@@ user_config @@}}" || echo "{{@@ dfl_config @@}}"
variables:
  user_config: "profile_{{@@ user @@}}_uid.yaml"
  dfl_config: "profile_default.yaml"
profiles:
  p1:
    dotfiles:
    - f_abc
    import:
    - "{{@@ config_file @@}}"
```

see also:

* <https://github.com/deadc0de6/dotdrop/wiki/config>
* <https://github.com/deadc0de6/dotdrop/wiki/config-variables>
* <https://github.com/deadc0de6/dotdrop/wiki/config#import-profile-dotfiles-from-file>
