### ISSUE TITLE
[feature] Profile-scoped `import_variables`

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#194]
# Use case
Let's start with my use case.

I have some variables, with two sets of different values, one for my *personal* setup and one for my *work* setup. I would like them to be included in two different profiles, creatively named `personal` and `work`. For privacy reasons I want to encrypt the variables, so I save them in two separate YAML files encrypted independently of dotdrop via `git-secret`.

# What I am trying to achieve
I need the two set of variables to be profile variables, as the variable names are the same but the values change. However, they cannot be listed directly in the profile-specific `variables` key in the YAML config file due to the privacy restrictions described above. Importing the two YAML files via `import_variables` is also not feasible, as one file would overwrite the other, since they define the same variable names.

# What I have tried so far
One solution is to use full-blown config files rather than variables files. There, I grouped the variables in a profile (`work-variables` and `personal-variables`). These files are then encrypted with `git-secret` and imported via `import_configs`, and the `*-variables` profiles included in the "main" profile (eg. `work-variables` is included in `work`). Basically I use the `*-variables` profile to create namespaces for variables. Here you have the files.

```yaml
# config.yaml

config:
  import_configs:
  - work.yaml
  - personal.yaml

profiles:
  personal:
    include:
    - personal-variables
  work:
    include:
    - work-variables
```
```yaml
# personal.yaml

profiles:
  personal-variables:
    variables:
      email: personal@email.me
```
```yaml
# work.yaml

profiles:
  work-variables:
    variables:
      email: work@email.com
```

# The feature
My actual use case is a bit more complex than this, so I'm okay with this setup. However, this process is a bit *verbose*, since it requires:

- Using full-blown YAML config files, with a redundant `config` section and all the rest. Yes, all the `*-variables` profiles could be in the same file, but if it needs to be split for some other reason then there's a lot of boilerplate
- Creating profiles for each set of variables.
- Including them in the profiles in the main YAML config file.

It would be easier, and a bit more intuitive, to have `import_variables` working at profile scope, like this:
```yaml
profiles:
  funky-profile:
    import_variables:
    - funky-variables.yaml
```
It would also match the `import` key already available for importing dotfiles from external YAML files at profile scope

**Comment by deadc0de6** [comment]
I see, what about using templating in the config file itself to define which config file with the variables to import?

Something like this:
```yaml
# config.yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
  import_configs:
  - "{{@@ profile @@}}.yaml"
profiles:
  personal:
    dotfiles:
    - something
  work:
    dotfiles:
    - something_else
dotfiles:
   ...
```

```yaml
# work.yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
  variables:
  - email: work@email.com
dotfiles:
profiles:
```

```yaml
# personal.yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
  variables:
  - email: personal@email.me
dotfiles:
profiles:
```
