### ISSUE TITLE
[feature] Ignore README.md files in dotfiles folder

### ISSUE THREAD

**Issue by raember** [deadc0de6/dotdrop#195]
I would like to have an explanation or comments inside the `dotfiles` folder and its children to clarify things like package dependencies/dotfile dependencies or other special cases, as one big readme file at the root can get cumbersome to maintain and immediately see whether there are special remarks for specific dotfiles or not. This gives me and potentially others the ability to see my remarks when they are browsing my dotfiles on github or locally. I further want those `README.md` files not to be installed into my system when I issue `dotdrop install` nor for them to show up when I run `dotdrop compare`.
To solve this, I would like to have a global or dotfile-level `ignore` configuration where I can list patterns to completely be ignored by dotdrop or have an even simpler `ignorereadme: true`.

example:
```
dotfiles
└── .config
    ├── bspwm
    |   ├── bspwmrc
    |   └── README.md  <- ignored
    ├── compton.conf
    └── README.md  <- ignored
```

**Comment by deadc0de6** [comment]
Thanks for submitting this. Currently you can already control patterns to ignore for **compare** (`cmpignore`) and for **update** (`upignore`). See [the config format in the wiki](https://github.com/deadc0de6/dotdrop/wiki/config#format).

I have added `instignore` in the [instignore branch](https://github.com/deadc0de6/dotdrop/tree/instignore) for **install**. Can you give it a try? It should work exactly like `cmpignore` and `upignore`, that is you should be able to do something like this:
```yaml
config:
  instignore:
  - README.md
...
``` 

or directly in dotfiles
```yaml
dotfiles:
  d_bspwm:
    dst: ~/.config/bspwm
    src: config/bspwm
    instignore:
    - README.md
...
```

**Comment by raember** [comment]
Thank you very much for your fast patch. It indeed does not install the README file into my system.
But despite me setting `cmpignore`, dotdrop points out that the README file does not exist in my system:
```
$ dotdrop compare
=> compare d_environment.d: diffing with "/home/re/.config/environment.d"
=> "README.md" does not exist on local
```
Could I extend my feature request to having the comparison ignore those files that are flagged by `instinstall`? That would be a nice-to-have imo.

Thank you!

**Comment by deadc0de6** [comment]
Have you tried to use an explicit ignore pattern, like `*/README.md`?

**Comment by deadc0de6** [comment]
Something like this
```yaml
config:
  cmpignore:
  - '*/README.md'
  upignore:
  - '*/README.md'
  instignore:
  - '*/README.md'
```
