### ISSUE TITLE
[bug] Custom functions and filters not available in dotfile YAML entries

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#210]
Dotdrop version (and git commit if run from source): b56e8ea
Using dotdrop: as a submodule

I'm not even sure this is a bug, it's probably intentional :smile: Shortly, custom functions and filter imported via `func_file` and `filter_file` are not available in YAML config files, but only in dotfiles.

For example, given this filter file snippet

```python
def prefix_config(path: str) -> str:
    return str(PurePath(os.environ['XDG_CONFIG_HOME']) / path)
```
This config file snippet fails
```yaml
config:
  filter_file:
  - /path/to/filter/file.py
dotfiles:
  fancy-dotfile:
    src: config/fancy-dotfile
    dst: "{{@@ 'fancy-dotfile' | prefix_config @@}}"
```

With this error
```
jinja2.exceptions.TemplateAssertionError: no filter named 'prefix_config'
```
---

I understand that allowing this might lead to nasty corner cases, like this:
```yaml
config:
  filter_file:
  - "{{@@ filter_file_prefix @@}}/my_custom_filter.py"
variables:
  filter_file_prefix: "{{@@ 'filters' | my_custom_filter @@}}"
```
Where `my_custom_filter` is defined in `my_custom_filter.py`

If custom filters and functions in YAML files are intentionally not allowed for cases like these, or even worse, that should be stated in the documentation.
