### ISSUE TITLE
[help] ignore pattern not wrok

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#217]
**What I am trying to achieve**

Say I have a file `conf.yml`, after import the config.yaml of dotdrop updated to:

```
dotfiles:
  f_conf.yml:
    src: config/cheat/conf.yml
    dst: ~/.config/cheat/conf.yml
```

And I want ignore compare from now on.

**What I have tried so far**

I have below setting now

```
config:
  cmpignore:
  - f_conf.yml
  - 'dotfiles/config/cheat/conf.yml'
```

But neither them works.

**Comment by deadc0de6** [comment]
what about that:
```yaml
dotfiles:
  f_conf.yml:
    src: config/cheat/conf.yml
    dst: ~/.config/cheat/conf.yml
    cmpignore:
    - "*"
```
