### ISSUE TITLE
[help] how to supress message saying: does not exist on local.

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#219]
**What I am trying to achieve**

I use dotdrop import a file, but I just wanna removed it from local temporary, but maybe reinstall it back, I wanna use cmpignore and instignore to make it:

```
  f_gadgets.json:
    src: vim/pack/vimspector/opt/vimspector/gadgets/linux/.gadgets.json
    dst: ~/.vim/pack/vimspector/opt/vimspector/gadgets/linux/.gadgets.json
    cmpignore:
    - '*'
    instignore:
    - '*'
```

But I got

```
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.32.0
                               |_|

=> compare f_gadgets.json: "/home/roach/.vim/pack/vimspector/opt/vimspector/gadgets/linux/.gadgets.json" does not exist on local
```

Is there a way to supress the notification?
