### ISSUE TITLE
[feature] if profile contains in a list or set then install corresponding section.

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#223]
Hi, I've found the `include` at #12 

But for me not perfect. As there is a dot file:

```
{%@@ if profile == "hwina" @@%}
...
{%@@ endif @@%}
{%@@ if profile == "hmank" @@%}
some_thing
{%@@ endif @@%}
```

And now I have a new PC and profile is `hmanx`, I want to create a variable `manjaro_profiles` then the config will change to:

```
{%@@ if profile == "hwina" @@%}
...
{%@@ endif @@%}
{%@@ if profile in manjaro_profiles @@%}
some_thing
{%@@ endif @@%}
```

And `manjaro_profiles` equals to `{hmank, hmanx}`.

The `some_thing` will also install to profile hmanx.

**Comment by deadc0de6** [comment]
I'm not sure to understand your feature request, this is already doable:

```
{%@@ if profile == "p1" @@%}
p1
{%@@ endif @@%}

{%@@ if profile in othersvar @@%}
others
{%@@ endif @@%}
```

config.yaml
```yaml
variables:
  othersvar: "p2 p3"
dotfiles:
  f_test:
    src: test
    dst: ~/.test
profiles:
  p1:
    dotfiles:
    - f_test
  p2:
    dotfiles:
    - f_test
  p3:
    dotfiles:
    - f_test
```

What did you try?
