### ISSUE TITLE
[help] remove comment begin with "

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#224]
**What I am trying to achieve**

I wanna remove comment begin with `"`, like in .vimrc

**What I have tried so far**

adding

```
actions:
  post:
    remove-doublequote-comment: sed -i '/^".*/d' {0}
```
to config.yaml, got error

```
[WARN] bad action: "sed -i '/^".*/d' {0}" with "[]" 
[ERR] post-action "remove-doublequote-comment" failed 
```

Also try to use:

```
actions:
  post:
    remove-doublequote-comment: "sed -i '/^# my pattern$/,$d' {0}"
```

according to [append · deadc0de6/dotdrop Wiki](https://github.com/deadc0de6/dotdrop/wiki/append)

got error:

```
[WARN] bad action: "sed -i '/^".*$/,$d' {0}" with "[]" 
[ERR] post-action "remove-doublequote-comment" failed 
```

**Comment by deadc0de6** [comment]
You probably should have quoted the internal double-quotes (`\"` as used below).

It also work with transformation:
```yaml
trans_read:
  remove-doublequote-comment: "sed '/^\".*/d' {0} > {1}"
dotfiles:
  f_test:
    src: test
    dst: ~/.test
    trans_read: remove-doublequote-comment
```

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/80785840-381cb100-8bb4-11ea-9d2f-1a44b33e34e5.png)

Thanks for your reply! Still got an error!

**Comment by deadc0de6** [comment]
You didn't print your entire config but I'm guessing you are not providing the requested argument to the action (since you used `{0}` you should provide an argument to the action when calling it in the dotfile).

Here's a working example that circumvent that issue:
```yaml
actions:
  post:
    remove-doublequote-comment: "sed -i '/^\".*/d' {{@@ _dotfile_abs_dst @@}}"
dotfiles:
  f_test:
    src: test
    dst: ~/.test
    actions:
    - remove-doublequote-comment
```

**Comment by roachsinai** [comment]
> You didn't print your entire config but I'm guessing you are not providing the requested argument to the action (since you used `{0}` you should provide an argument to the action when calling it in the dotfile).
> 
> Here's a working example that circumvent that issue:
> 
> ```yaml
> actions:
>   post:
>     remove-doublequote-comment: "sed -i '/^\".*/d' {{@@ _dotfile_abs_dst @@}}"
> dotfiles:
>   f_test:
>     src: test
>     dst: ~/.test
>     actions:
>     - remove-doublequote-comment
> ```

Works now! Thanks a lot.

**Comment by roachsinai** [comment]
But for transformation, setting below not works for the file `include` in ~.test.

```
trans_read:
  remove-doublequote-comment: "sed '/^\".*/d' {0} > {1}"
dotfiles:
  f_test:
    src: test
    dst: ~/.test
    trans_read: remove-doublequote-comment
```

I mean if have things like `{%@@ include 'maps.txt' @@%}, the comment in maps.txt still in finally ~/.test.
