### ISSUE TITLE
[feature] Secret variable

### ISSUE THREAD

**Issue by Asteb612** [deadc0de6/dotdrop#228]
My goal is to get the password only once and use it to decrypt multiple files.
That work but the password is showed on command log. [Here](https://github.com/deadc0de6/dotdrop/blob/fb9410eda641f2cd96864902004f72b277148977/dotdrop/action.py#L56)

Today i show the command without parameter resolution `self.action` but i think a better solution are available.

```
config:
  backup: true
  create: true
  dotpath: dotfiles
dynvariables:
  gpg_password: "./get-password.sh | openssl enc -base64"
dotfiles:
  f_secret1:
    src: secret1.gpg
    dst: ~/.secret1
    trans_read: gpg
  f_secret2:
    src: secret2.gpg
    dst: ~/.secret2
    trans_read: gpg
  f_secret3:
    src: secret3.gpg
    dst: ~/.secret3
    trans_read: gpg
profiles:
  meilleursagents:
    dotfiles:
    - f_secret1
    - f_secret2
    - f_secret3
trans_read:
  gpg: echo '{{@@ gpg_password @@}}' | openssl enc -base64 -d | gpg2 --batch --yes --passphrase-fd 0 -q --for-your-eyes-only --no-tty -d {0} > {1}
```

**Comment by deadc0de6** [comment]
What about using the password directly using gpg's switch `--passphrase-file`?

using `--passphrase-file`
```yaml
variables:
  gpg_password: "./get-password.sh"
trans_read:
  gpg: "gpg2 --batch --yes --passphrase-file <({{@@ gpg_password @@}}) -q --for-your-eyes-only --no-tty -d {0} > {1}"
```

or directly with the passphrase stored in a file
```yaml
variables:
  gpg_password_file: "/tmp/the-password"
trans_read:
  gpg: "gpg2 --batch --yes --passphrase-file <(cat {{@@ gpg_password_file @@}}) -q --for-your-eyes-only --no-tty -d {0} > {1}"
```

**Comment by Asteb612** [comment]
To the first solution with the process substitution `<()` this feature is not usable in `/bin/sh`.
And the command `./get-password.sh` is called each time and not cached.

Based on your second solution i have tried this.
```
actions:
   post:
      clean: rm /tmp/pass
   pre:
      gpg_password: "./get-password.sh > /tmp/pass"
profiles:
  secret:
    actions:
    - gpg_password
    - clean
trans_read:
  gpg-passworg: gpg2 --batch --yes --passphrase-file /tmp/pass -q --for-your-eyes-only --no-tty -d {0} > {1}
```
The only small problem is if no file are installed the post command are not called and the file is not removed.

Another solution can be store all variable with prefix `s_` in temp files created and removed by dotdrop internally. And on command execution, the jinja resolution return the temp file path and not the variable content. If you are good with that i can create a PR ?
