### ISSUE TITLE
[bug] --dry changes config file on import

### ISSUE THREAD

**Issue by kluen** [deadc0de6/dotdrop#237]
Dotdrop version (and git commit if run from source): 6474a48 (current master)
Using dotdrop: as a submodule

**Describe the bug**

When running an import with `--dry`, the changes are applied to the `config.yaml` instead of only being printed.

**Steps to Reproduce**

1. `touch ~/foo && dotdrop import --dry ~/foo`
2. See that the `config.yaml` was changed

**Expected behavior**

The `config.yaml` should not be changed.

**Additional information**

I found that this is due to the fact that [the relevant code in dotdrop.py](https://github.com/deadc0de6/dotdrop/blob/6474a48961ef3be0c572b740f2a48834996871b3/dotdrop/dotdrop.py#L433-L443) assumes that the change of the config is not applied until `save()` is called on it. However, it saves and reloads the config already in [the `new()` function](https://github.com/deadc0de6/dotdrop/blob/6474a48961ef3be0c572b740f2a48834996871b3/dotdrop/cfg_aggregator.py#L178-L186).

I was wondering if the saving and reloading is needed at all. If it is ok to be deleted, I could provide a PR.

**Comment by deadc0de6** [comment]
The reason the `new()` function does reload the whole config is to make sure the view of the config as seen by dotdrop is up-to-date (for more see [this doc](https://github.com/deadc0de6/dotdrop/blob/master/CONTRIBUTING.md)).

There are two main ways to fix the `--dry` changing the config file:

* not providing the user with `new config file would be`
* not reloading the config for this specific case on `new` but that means the view of the config is altered and some side effects may occur

I'm in favor of the first one but a user using `--dry` wouldn't be able to preview what the changes to the config would be. An advantage of having `--dry` changing the config is that since it's git versioned, it is easy to revert but I agree it is not optimal.

What do you think?

**Comment by deadc0de6** [comment]
I fixed the config file being changed when `--dry` is used in branch [dry-import](https://github.com/deadc0de6/dotdrop/tree/dry-import). Also now the *temporary* changed config is more clearly displayed.
```yaml
[DRY] new config file would be: 
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_test:
    src: test
    dst: ~/.test
profiles:
  hostname:
    dotfiles:
    - f_test
```
