### ISSUE TITLE
[Help] Even with upignore, dotdrop still copies the ignored folders to the dotfiles

### ISSUE THREAD

**Issue by gusbemacbe** [deadc0de6/dotdrop#241]
**What I am trying to achieve**

- Command;

```zsh
dotdrop update ~/.config/Colorpicker -p "gusbemacbe-x370gt7" --cfg="configuração-pasta-pessoal.yaml"
```

- Config template:

```yaml
  d_config_colorpicker:
    src: .config/Colorpicker
    dst: ~/.config/Colorpicker
    upignore:
      - ".config/Colorpicker/blob_storage"
      - ".config/Colorpicker/Code Cache"
      - ".config/Colorpicker/GPUCache"
      - ".config/Colorpicker/Session Storage"
```

I also tried other ways:

```yaml
    upignore:
      - "~/.config/Colorpicker/blob_storage"
      - "~/.config/Colorpicker/Code Cache"
      - "~/.config/Colorpicker/GPUCache"
      - "~/.config/Colorpicker/Session Storage"
```

And

```yaml
    upignore:
      - "$HOME/.config/Colorpicker/blob_storage"
      - "$HOME/.config/Colorpicker/Code Cache"
      - "$HOME/.config/Colorpicker/GPUCache"
      - "$HOME/.config/Colorpicker/Session Storage"
```

In all these way, when I updated to my dotfiles, dotdrop still copied these ignored/unnecessary folders.

**Comment by deadc0de6** [comment]
Try this:
```yaml
  d_colorpicker:
    src: config/Colorpicker
    dst: ~/.config/Colorpicker
    upignore:
      - '*blob_storage'
      - '*Code Cache'
      - '*GPUCache'
      - '*Session Storage'
```

**Comment by gusbemacbe** [comment]
Hello @deadc0de6 

Thank you a lot. I have just tested with your sample, and it worked with:

```yaml
  d_config_googlechrome:
    src: .config/google-chrome-unstable
    dst: ~/.config/google-chrome-unstable
    upignore:
    # Folders
    - BrowserMetrics
    - CertificateRevocation
    - Crash Reports
    - Crowd Deny
    - ECSerivceProvidersConfig
    - FileTypePolicies
    - GrShaderCache
    - InterventionPolicyDatabase
    - MEIPreload
    - NativeMessagingHosts
    - OriginTrials
    - PepperFlash
    - pnacl
    - Safe Browsing
    - SafetyTips
    - ShaderCache
    - SSLErrorAssistant
    - Subresource Filter
    - TLSDeprecationConfig
    - Webstore Downloads
    - WidevineCdm

    # Files
    - BrowserMetrics-spare.pma
    - Consent To Send Stats
    - First Run
    - Last Version
    - Safe Browsing Cookies
    - Safe Browsing Cookies-journal

    # Subfolders of folder Default
    - '*AutofillStrikeDatabase'
    - '*blob_storage'
    - '*BudgetDatabase'
    - '*Code Cache'
    - '*data_reduction_proxy_leveldb'
    - '*databases'
    - '*Extension Rules'
    - '*Extension State'
    - '*Feature Engagement Tracker'
    - '*File System'
    - '*GCM Store'
    - '*GPUCache'
    - '*IndexedDB'
    - '*Local Extension Settings'
    - '*Local Storage'
    - '*Platform Notifications'
    - '*Service Worker'
    - '*Session Storage'
    - '*shared_proto_db'
    - '*Site Characteristics Database'
    - '*Session Storage'
    - '*Sync Data'
    - '*Sync Extension Settings'
    - '*VideoDecodeStats'

    # Files of folder Default
    - '*Cookies'
    - '*Cookies-journal'
    - '*Current Session'
    - '*Current Tabs'
    - '*heavy_ad_intervention_opt_out.db'
    - '*heavy_ad_intervention_opt_out.db-journal'
    - '*History'
    - '*History Provider Cache'
    - '*History-journal'
    - '*Last Session'
    - '*Last Tabs'
    - '*LOCK'
    - '*LOG'
    - '*LOG.old'
    - '*Login Data'
    - '*Login Data-journal'
    - '*Media History'
    - '*Media History-journal'
    - '*Network Action Predictor'
    - '*Network Action Predictor-journal'
    - '*previews_opt_out.db'
    - '*previews_opt_out.db-journal'
    - '*QuotaManager'
    - '*QuotaManager-journal'
    - '*README'
    - '*Reporting and NEL'
    - '*Reporting and NEL-journal'
    - '*Shortcuts'
    - '*Shortcuts-journal'
    - '*Top Sites'
    - '*Top Sites-journal'
    - '*Translate Ranker Model'
    - '*TransportSecurity'
    - '*Visited Links'
    - '*Web Data'
    - '*Web Data-journal'
```
