### ISSUE TITLE
[Help] Don't actions support the normal shell?

### ISSUE THREAD

**Issue by gusbemacbe** [deadc0de6/dotdrop#242]
Hello

I have been training with https://github.com/deadc0de6/dotdrop/wiki/usage-actions. 

Observe that I do not use `link` because I do not symlink my dotfiles. I want to symlink the folder `~/.config/folder` to `~/.config/folder-alt`, for example:

```yaml
  d_config_opera:
    src: .config/opera
    dst: ~/.config/opera
    actions:
        - ln -sfnr ~/.config/opera ~/.config/opera-developer
```

I also tried, using `pre` and `post` too, but the actions did not work either.

**Comment by deadc0de6** [comment]
That's not the way you have to define actions. Actions are first defined in their own entry (see [config format doc](https://github.com/deadc0de6/dotdrop/wiki/config#format)) and then used in the dotfiles.

For your use-case, this would work:
```yaml
actions:
  linkdir: 'ln -sfnr {{@@ _dotfile_abs_dst @@}} {{@@ _dotfile_abs_dst @@}}-developer'
dotfiles:
  d_folder:
    src: config/folder
    dst: ~/.config/folder
    actions:
      - linkdir
```

Here I used templates variables (as explained [here](https://github.com/deadc0de6/dotdrop/wiki/templating#dotfile-variables)) but you could as well use directly the directory or even pass as argument.
```yaml
actions:
  linkdir: 'ln -sfnr {0} {0}-developer'
dotfiles:
  d_folder:
    src: config/folder
    dst: ~/.config/folder
    actions:
      - linkdir '{{@@ _dotfile_abs_dst @@}}'
```

**Comment by gusbemacbe** [comment]
I ran it, but your dotdrop did not symlink. I refreshed, and it did not symlink.

```yaml
actions:
  linkdir_opera: 'ln -sfnr {0} {0}-developer'
config:
  backup: false
  banner: true
  create: true
  dotpath: home
  ignoreempty: false
  keepdot: true
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_config_opera:
    src: .config/opera
    dst: ~/.config/opera
    actions:
      - linkdir_opera '{{@@ _dotfile_abs_dst @@}}'
```

And I ran the command:

```
dotdrop install d_config_opera -p "gusbemacbe-x370gt7" --cfg="configuração-pasta-pessoal.yaml"
```

The result:

```zsh
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v1.1.0
                               |_|
	-> executing "ln -sfnr /home/gusbemacbe/.config/opera /home/gusbemacbe/.config/opera-developer"
```

The screenshot where you can see the folder `opera-developer` is not created:

![image](https://user-images.githubusercontent.com/2257024/85236807-83ef1800-b3f7-11ea-9553-3345deb7fdd0.png)

Maybe because of

```yaml
  link_dotfile_default: nolink
  link_on_import: nolink
```
?
