### ISSUE TITLE
[Help] The link_children does not preserve the symlinks.

### ISSUE THREAD

**Issue by gusbemacbe** [deadc0de6/dotdrop#243]
Hello

When I update a folder, which has a lot of symlinks, your dotdrop deferences them and copies the original folders. I would like to preserve symlinks. You can see a small configuration:

```yaml
  d_vscode:
    src: .vscode-insiders
    dst: ~/.vscode-insiders
    link: link_children
    upignore:
      - extensions
```

Compare the destination screenshot as you can see a lot of symlinks:

![image](https://user-images.githubusercontent.com/2257024/85219999-95e0a480-b37e-11ea-8c33-f9e7e8ba7007.png)

To this source screenshot, as you can see the folders are not anymore symlinks because your dotdrop deferenced them and copied the original folders:

![image](https://user-images.githubusercontent.com/2257024/85220034-dd673080-b37e-11ea-9bf7-77a208389775.png)

**Comment by deadc0de6** [comment]
Dotdrop will dereference symlinks when importing as mentioned [in the import doc](https://github.com/deadc0de6/dotdrop/wiki/usage#import-dotfiles). That means dotdrop won't store symlinks in the dotpath (and thus installing the dotfile will replace symlinks by the actual directory).

You can have a look at [this discussion](https://github.com/deadc0de6/dotdrop/issues/184) for more info.

Without more information it's difficult for me to help but where are those links pointing to? Do you absolutely need to keep symlinks?
Another approach would be to import the directories those symlinks are pointing to in the first place and using actions or something similar to set symlinks during installation. Would that be doable?

**Comment by gusbemacbe** [comment]
> Without more information it's difficult for me to help but where are those links pointing to? Do you absolutely need to keep symlinks?

Yes, I do. They are pointed to `~/.vscode-insiders/extensions`:

![image](https://user-images.githubusercontent.com/2257024/85236986-50ad8880-b3f9-11ea-88a1-cf5abe5b1bae.png)

1. At `~/.vscode-insiders/`, I created a `workspaces` folder, 
2. At `~/.vscode-insiders/workspaces`, I created the folders for specific templates by language, for example, `basic markdowm` and `php+css+html`, in reference to https://github.com/microsoft/vscode/issues/90649, but Microsoft did not add that feature yet.
3. At these templates, I symlinked some determined extensions, for example, specific PHP extensions for the template folder `php+css+html`.

I created an alias for opening the specific PHP project with VSCode with PHP template:

```shell
alias code-php="code-insiders --extensions-dir='/home/gusbemacbe/.vscode-insiders/workspaces/php+html+css'"
```

And

```zsh
code-php ~/Projects/site-php
```

It opens only with some enabled PHP extensions, and not with all extensions. 

It is important to observe that `~/.vscode-insiders/extensions` loads more than 3GB, it is not good to copy the whole extensions folder to my dotfiles, to duplicate the original for workspaces templates, or and your dotdrop to copy and duplicate the deferenced extensions folders.

**Comment by deadc0de6** [comment]
I see so you don't actually want to managed those directories with dotdrop but only use dotdrop to create those symlinks if I understand correctly.

What about creating a *fake* dotfile that will run the creation of those symlinks?
Something similar to this:
```yaml
actions:
  code_symlink: 'ln -s ~/.vscode-insiders/extensions/{0} ~/.vscode-insiders/{0}'
dotfiles:
  fake:
    src:
    dst:
    actions:
      - code_symlink 'extension1'
      - code_symlink 'extension2'
      - code_symlink 'extension3'
```

Would that work for your use-case?

**Comment by gusbemacbe** [comment]
> I see so you don't actually want to managed those directories with dotdrop but only use dotdrop to create those symlinks if I understand correctly.

Actually, I want your dotdrop to copy **pure** symlinks via `update` to source and paste **pure** symlinks to destintation. 

But if your dotdrop does not support it, maybe I will use your sample template, but it will be too big. Maybe

```yaml
actions:
  code_dir: 'mkdir -p ~/.vscode-insiders/workspaces/{basic\ markdowm,php+css+html}'
  code_symlink_markdowm: 'ln -s ~/.vscode-insiders/extensions/{4gray.vsc-covid-stats-0.2.0,ban.spellright-3.0.50,bierner.github-markdown-preview-0.0.2,bierner.markdown-checkbox-0.1.3,bierner.markdown-emoji-0.0.9,bierner.markdown-preview-github-styles-0.1.6,dustinsanders.an-old-hope-theme-vscode-4.3.0,equinusocio.vsc-community-material-theme-1.4.1,equinusocio.vsc-material-theme-32.6.0,equinusocio.vsc-material-theme-icons-1.1.4,evan-buss.font-switcher-3.1.0,fcrespo82.markdown-table-formatter-2.0.4,formulahendry.auto-rename-tag-0.1.3,funkyremi.vscode-google-translate-1.4.5,guillaumedoutriaux.name-that-color-0.1.2,ms-ceintl.vscode-language-pack-en-gb-1.46.3,ms-vscode.atom-keybindings-3.0.8,naumovs.color-highlight-2.3.0,pkief.material-icon-theme-4.2.0,remimarsal.prettier-now-1.4.9,rid9.datetime-2.0.1,searking.preview-vscode-2.1.0,slevesque.vscode-zipexplorer-0.3.1,vincaslt.highlight-matching-tag-0.9.9,wakatime.vscode-wakatime-4.0.0,wmaurer.change-case-1.0.0,ysemeniuk.emmet-live-1.0.0,yzhang.markdown-all-in-one-3.0.0} ~/.vscode-insiders/workspaces/basic\ markdowm/{0}'
  code_symlink_php: 'ln -s ~/.vscode-insiders/extensions/{abusaidm.html-snippets-0.2.1,brapifra.phpserver-2.4.6,dbaeumer.vscode-eslint-2.1.5,dustinsanders.an-old-hope-theme-vscode-4.3.0,ecmel.vscode-html-css-0.2.3,eiminsasete.apacheconf-snippets-1.3.0,equinusocio.vsc-material-theme-32.6.0,equinusocio.vsc-material-theme-icons-1.1.4,evan-buss.font-switcher-3.1.0,felixfbecker.php-debug-1.13.0,felixfbecker.php-intellisense-2.3.14,formulahendry.auto-rename-tag-0.1.3,funkyremi.vscode-google-translate-1.4.5,guillaumedoutriaux.name-that-color-0.1.2,henriiik.vscode-sort-0.2.5,jasonlhy.vscode-browser-sync-1.3.1,junstyle.php-cs-fixer-0.1.154,mrmlnc.vscode-apache-1.2.0,mrmlnc.vscode-attrs-sorter-2.1.0,mrmlnc.vscode-csscomb-5.3.1,mrmlnc.vscode-duplicate-1.2.1,ms-ceintl.vscode-language-pack-en-gb-1.46.3,ms-vscode.atom-keybindings-3.0.8,naumovs.color-highlight-2.3.0,nkokhelox.svg-font-previewer-1.1.5,ohansemmanuel.css-grid-snippets-0.0.5,pkief.material-icon-theme-4.2.0,pranaygp.vscode-css-peek-3.0.2,redhat.vscode-xml-0.12.0,remimarsal.prettier-now-1.4.9,rid9.datetime-2.0.1,searking.preview-vscode-2.1.0,slevesque.vscode-zipexplorer-0.3.1,vincaslt.highlight-matching-tag-0.9.9,wwm.better-align-1.1.6,xadillax.viml-1.0.0,xiangdong-zeng.fontforge-vscode-0.0.2,ysemeniuk.emmet-live-1.0.0,yzane.markdown-pdf-1.4.4,yzhang.markdown-all-in-one-3.0.0,zhouronghui.propertylist-0.0.2,zignd.html-css-class-completion-1.19.0} ~/.vscode-insiders/workspaces/php+html+css/{0}'
dotfiles:
  fake:
    src:
    dst:
    actions:
      - code_dir
      - code_symlink_markdowm
      - code_symlink_php
```

It would work with `dotdrop install`. The problem is with `dotdrop update`. I think I have to add `upignore` for preventing from deferencing and copying the deferenced folders. 

If I want to update, maybe this template would be like:

```yaml
actions:
  code_copy: 'cp -r ~/.vscode-insiders/workspaces ~/meus-dotfiles/home/.vscode-insiders/'
dotfiles:
  fake:
    src:
    dst:
    actions:
    # via install
      pre:
        - code_dir
        - code_symlink_markdowm
        - code_symlink_php
    # via update
      pos: 
        - code_copy
```

**Comment by deadc0de6** [comment]
Well yes you actually hit one of the limitation of dotdrop. It doesn't handle symlinks this way for the reasons mentioned [here](https://github.com/deadc0de6/dotdrop/issues/184#issuecomment-524645829).

However you could improve that a bit with a combination of some files, variables, dynvariables and actions for dynamically creating the needed symlinks. `update` could be managed manually by simply adding/removing a line in a file. For example:

The file `<dotdrop-dir>/basic_markdown.txt` contains all markdown extensions (I put only 3 here for the example)
```
4gray.vsc-covid-stats-0.2.0
ban.spellright-3.0.50
bierner.github-markdown-preview-0.0.2
```

the file `<dotdrop-dir>/php_css_html.txt` contains all php/css/html extensions (I put only 3 here for the example)
```
abusaidm.html-snippets-0.2.1
brapifra.phpserver-2.4.6
dbaeumer.vscode-eslint-2.1.5
```

the config file will load the above files content using dynvariables and install these using a *fake* dotfile and a generic action.
```yaml
dynvariables:
  basic_markdown_exts: "cat basic_markdown.txt | xargs"
  php_css_html_exts: "cat php_css_html.txt | xargs"
variables:
  vscode_workspaces: "~/.vscode-insiders/workspaces"
  basic_markdown_dst: "{{@@ vscode_workspaces @@}}/basic\ markdowm/"
  php_css_html_dst: "{{@@ vscode_workspaces @@}}/php+html+css/"
actions:
  symlink_extensions: 'for ext in {0}; do ln -s {{@@ vscode_workspaces @@}}/$ext {1}/$ext; done'
dotfiles:
  fake:
    src:
    dst:
    actions:
      - symlink_extensions '{{@@ basic_markdown_exts @@}} {{@@ basic_markdown_dst @@}}'
      - symlink_extensions '{{@@ php_css_html_exts @@}} {{@@ php_css_html_dst @@}}'
```

I haven't tested it but this gives you an idea on how you could do it. It is not perfect but allows you to more easily manage your extensions using simple text files.

**Comment by gusbemacbe** [comment]
The only problem that the folder `workspaces` and subfolders `basic markdowm` and `php+css+html` need to be created when install, because it is me who creates these folders, not Microsoft and they do not exist on the default `~/.vscode-insiders/`

> ```yaml
> symlink_extensions: 'for ext in {0}; do ln -s {{@@ vscode_workspaces @@}}/$ext {1}/$ext; done
>

Actually the extensions are installed on `~/.vscode/extensions` and not on `~/.vscode/workspaces`. I would write like:

```yaml
symlink_extensions: 'for ext in {0}; do ln -s ~/vscode-insiders/extensions/$ext {{@@ vscode_workspaces @@}}//$ext; done
```

Is it correct?

**Comment by deadc0de6** [comment]
I added the creation of the directories in the action (`mkdir -p {1}` which translates for example to `mkdir -p ~/.vscode-insiders/workspaces/basic\ markdowm/`) and fixed the source to `~/.vscode-insiders/extensions`.
```yaml
dynvariables:
  basic_markdown_exts: "cat basic_markdown.txt | xargs"
  php_css_html_exts: "cat php_css_html.txt | xargs"
variables:
  vscode_workspaces: "~/.vscode-insiders/workspaces"
  vscode_extensions: "~/.vscode-insiders/extensions"
  basic_markdown_dst: "{{@@ vscode_workspaces @@}}/basic\ markdowm/"
  php_css_html_dst: "{{@@ vscode_workspaces @@}}/php+html+css/"
actions:
  symlink_extensions: 'mkdir -p {1} && for ext in {0}; do ln -s {{@@ vscode_extensions @@}}/$ext {1}/$ext; done'
dotfiles:
  fake:
    src:
    dst:
    actions:
      - symlink_extensions '{{@@ basic_markdown_exts @@}} {{@@ basic_markdown_dst @@}}'
      - symlink_extensions '{{@@ php_css_html_exts @@}} {{@@ php_css_html_dst @@}}'
```

But again, I haven't tested this so it might need some refactoring, let me know if you need help.

**Comment by gusbemacbe** [comment]
> But again, I haven't tested this so it might need some refactoring, let me know if you need help.

You do not need to test. I test for you. I used `-t` to review the results. But the `fake` dotfile did not take in both commands:

```zsh
~/G/meus-dotfiles   órfão  dotdrop install fake -a -t -p "gusbemacbe-x370gt7" --cfg="configuração-pasta-pessoal.yaml"               (1s 174ms)  
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v1.1.0
                               |_|


installed to tmp "/tmp/dotdrop-vkgrcvf5".

1 dotfile(s) installed.
~/G/meus-dotfiles   órfão  dotdrop install d_vscode fake -a -t -p "gusbemacbe-x370gt7" --cfg="configuração-pasta-pessoal.yaml"         (458ms)  
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v1.1.0
                               |_|

	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/argv.json to /tmp/dotdrop-ef25attf/home/gusbemacbe/.vscode-insiders/argv.json
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/settings/csscomb.json to /tmp/dotdrop-ef25attf/home/gusbemacbe/.vscode-insiders/settings/csscomb.json
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/settings/php_cs.php to /tmp/dotdrop-ef25attf/home/gusbemacbe/.vscode-insiders/settings/php_cs.php
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/themes/emojione.css to /tmp/dotdrop-ef25attf/home/gusbemacbe/.vscode-insiders/themes/emojione.css
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/themes/markdown-styles.css to /tmp/dotdrop-ef25attf/home/gusbemacbe/.vscode-insiders/themes/markdown-styles.css
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/themes/nordic.css to /tmp/dotdrop-ef25attf/home/gusbemacbe/.vscode-insiders/themes/nordic.css
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/themes/an-old-hope.css to /tmp/dotdrop-ef25attf/home/gusbemacbe/.vscode-insiders/themes/an-old-hope.css
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/themes/markdown-pdf.css to /tmp/dotdrop-ef25attf/home/gusbemacbe/.vscode-insiders/themes/markdown-pdf.css

installed to tmp "/tmp/dotdrop-ef25attf".

2 dotfile(s) installed.
```

Maybe I misunderstood you suggested me to create a new fake dotfile and not inside the `d_vscode` dotfile.

**Comment by gusbemacbe** [comment]
Ah, I moved the actions to `d_vscode`, and it did not take actions to create symlinks. :-(

```
  d_vscode:
    src: .vscode-insiders
    dst: ~/.vscode-insiders
    upignore:
      - extensions
      - workspaces
    actions:
      - symlink_extensions '{{@@ basic_markdown_exts @@}} {{@@ basic_markdown_dst @@}}'
      - symlink_extensions '{{@@ php_css_html_exts @@}} {{@@ php_css_html_dst @@}}'
```

And

```zsh
dotdrop install d_vscode -a -t -p "gusbemacbe-x370gt7" --cfg="configuração-pasta-pessoal.yaml"              (638ms)  
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v1.1.0
                               |_|

	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/argv.json to /tmp/dotdrop-uvnk89ub/home/gusbemacbe/.vscode-insiders/argv.json
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/settings/csscomb.json to /tmp/dotdrop-uvnk89ub/home/gusbemacbe/.vscode-insiders/settings/csscomb.json
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/settings/php_cs.php to /tmp/dotdrop-uvnk89ub/home/gusbemacbe/.vscode-insiders/settings/php_cs.php
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/themes/emojione.css to /tmp/dotdrop-uvnk89ub/home/gusbemacbe/.vscode-insiders/themes/emojione.css
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/themes/markdown-styles.css to /tmp/dotdrop-uvnk89ub/home/gusbemacbe/.vscode-insiders/themes/markdown-styles.css
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/themes/nordic.css to /tmp/dotdrop-uvnk89ub/home/gusbemacbe/.vscode-insiders/themes/nordic.css
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/themes/an-old-hope.css to /tmp/dotdrop-uvnk89ub/home/gusbemacbe/.vscode-insiders/themes/an-old-hope.css
	-> copied /home/gusbemacbe/GitLab/meus-dotfiles/home/.vscode-insiders/themes/markdown-pdf.css to /tmp/dotdrop-uvnk89ub/home/gusbemacbe/.vscode-insiders/themes/markdown-pdf.css

installed to tmp "/tmp/dotdrop-uvnk89ub".

1 dotfile(s) installed.
```

**Comment by deadc0de6** [comment]
As long as the `fake` dotfile is in the profile you use, it will be executed, you don't need to move the actions to the `d_vscode` dotfile. But it is better to have it this way since it's related to vscode so it's better than have it in a loose dotfile. Both ways should work.

Can you provide me with the debug logs (run with `--verbose`) so I can better help?

**Comment by gusbemacbe** [comment]
> Can you provide me with the debug logs (run with `--verbose`) so I can better help?

[dotdrop_vscode.txt](https://github.com/deadc0de6/dotdrop/files/4813336/dotdrop_vscode.txt)

**Comment by deadc0de6** [comment]
a first issue is that you haven't created the `basic_markdown.txt` (or maybe not in the right place):
```
cat: basic_markdown.txt: Ficheiro ou pasta inexistente\n
```

The second one comes from the fact that the two arguments are taken as one in the action (need to have each argument enclosed in its own quotes: `'something' 'somethingelse'` instead of `'something somethingelse'`). The correct part:
```yaml
actions:
      - symlink_extensions '{{@@ basic_markdown_exts @@}}' '{{@@ basic_markdown_dst @@}}'
      - symlink_extensions '{{@@ php_css_html_exts @@}}' '{{@@ php_css_html_dst @@}}'
```

one additional fix would be to remove the trailing slash in the paths:
```yaml
variables:
  basic_markdown_dst: "{{@@ vscode_workspaces @@}}/basic\ markdowm"
  php_css_html_dst: "{{@@ vscode_workspaces @@}}/php+html+css"
```

I haven't however been able to figure out why your actions are not executed though. Can you please provide the config related to the above logs?

**Comment by gusbemacbe** [comment]
Hello @deadc0de6 

Sorry, I went to bed. I updated the dotdrop file with your corrections, but still an error:

```zsh
dotdrop install d_vscode fake -a -t -p "gusbemacbe-x370gt7" --cfg="configuração-pasta-pessoal.yaml"
[ERR] while constructing a mapping
  in "/home/gusbemacbe/GitLab/meus-dotfiles/configuração-pasta-pessoal.yaml", line 1, column 1
found duplicate key "actions" with value "["symlink_extensions '{{@@ basic_markdown_exts @@}}' '{{@@ basic_markdown_dst @@}}'", "symlink_extensions '{{@@ php_css_html_exts @@}}' '{{@@ php_css_html_dst @@}}'"]" (original value: "ordereddict([('linkdir_opera', 'ln -sfnr {0} {0}-developer'), ('symlink_extensions', 'mkdir -p {1} && for ext in {0}; do ln -s {{@@ vscode_extensions @@}}/$ext {1}/$ext; done'), ('vim-plug', 'nvim +PlugInstall +qall')])")
  in "/home/gusbemacbe/GitLab/meus-dotfiles/configuração-pasta-pessoal.yaml", line 929, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.
 
[ERR] config file error: invalid config: /home/gusbemacbe/GitLab/meus-dotfiles/configuração-pasta-pessoal.yaml 
```

I provided a zip, containing the folder `.vscode-insiders` with 6 extensions for you:

[deadc0de.zip](https://github.com/deadc0de6/dotdrop/files/4819107/deadc0de.zip)

**Comment by deadc0de6** [comment]
You have indentation issues:
```yaml
  fake:
    src:
    dst:
actions:
      - symlink_extensions '{{@@ basic_markdown_exts @@}}' '{{@@ basic_markdown_dst @@}}'
      - symlink_extensions '{{@@ php_css_html_exts @@}}' '{{@@ php_css_html_dst @@}}'
```

should be 

```yaml
  fake:
    src:
    dst:
    actions:
      - symlink_extensions '{{@@ basic_markdown_exts @@}}' '{{@@ basic_markdown_dst @@}}'
      - symlink_extensions '{{@@ php_css_html_exts @@}}' '{{@@ php_css_html_dst @@}}'
```

**Comment by deadc0de6** [comment]
There were multiple issues actually, here's the parts I fixed:

* `~` was not properly expanded, I used `{{@@ env['HOME'] @@}}` instead
* as usual filenames with spaces were messing the onliner
* moved the files containing the lists in the dotpath `mv basic_markdown.txt <your-dotpath>`

```yaml
dynvariables:
  basic_markdown_exts: "cat {{@@ _dotdrop_dotpath @@}}/basic_markdown.txt | xargs"
...
variables:   
  vscode_workspaces: "{{@@ env['HOME'] @@}}/.vscode-insiders/workspaces"
  vscode_extensions: "{{@@ env['HOME'] @@}}/.vscode-insiders/extensions"
  basic_markdown_dst: "{{@@ vscode_workspaces @@}}/basic markdowm"  
...
actions:
  symlink_extensions: 'mkdir -p "{1}" && for ext in {0}; do ln -s "{{@@ vscode_extensions @@}}/$ext" "{1}/$ext"; done'
...
  fake:
    src:
    dst:
    actions:
      - symlink_extensions '{{@@ basic_markdown_exts @@}}' '{{@@ basic_markdown_dst @@}}'
```

If you retry, please make sure you have only the `fake` dotfile in your profile (instead of `ALL`) so that logs are easier to parse (`--verbose`):
```yaml
profiles:
  gusbemacbe-x370gt7:
    dotfiles:
      - fake
```

Also make sure you use the latest version from master (I updated the debug logs to better help) and if that still doesn't work, please provide the log file (`--verbose`).
