### ISSUE TITLE
[Feature] Does your dotdrop support Ansible and elnappo/dotfiles' YAML files?

### ISSUE THREAD

**Issue by gusbemacbe** [deadc0de6/dotdrop#245]
Hello,

I was reading again the dotdrop's WIki pages:

- Import actions from file
- Import config files
- Dynamic dotfile paths 9like we did)
- Dynamic actions (like we did)
- Dynamic transformations
- Templating

I am not sure if these WIki pages work with @elnappo's YAML files. 

For example, some @elnappo's YAML files for:
- At Arch as OS profile:
   - for configuring `pacman.conf`;
   - for installing the packages via `pacman -S`;
   - for installing the AUR packages via `pacman -U`:
- At Arch or Ubuntu or any Linux distro, as Fedora, openSUSE and Void Linux:
   - adding user to Docker, etc;
- At macOS as another profile:
   - installing some macOS-specific dotfiles.
- At any OS, including macOS:
   - cloning Git{Hub,Lab} repositories, for example:

      ```yaml
         - name: Instalar o oh-my-fish
         git: repo=https://github.com/oh-my-fish/oh-my-fish.git dest=~/.local/share/omf update=yes

         - name: Instalar o gestor de plugins
         git: repo=https://github.com/tmux-plugins/tpm.git dest=~/.local/share/tpm update=yes

         - name: Instalar o dein.vim
         git: repo=https://github.com/Shougo/dein.vim.git dest=~/.local/share/dein/repos/github.com/Shougo/dein.vim update=yes
      ```
 
For example:

- https://github.com/elnappo/dotfiles/blob/master/ansible/tasks/arch.yml
- https://github.com/elnappo/dotfiles/blob/master/ansible/tasks/macos_defaults.yml
- https://github.com/elnappo/dotfiles/blob/master/ansible/tasks/packages.yml

Apt, AUR, pacman, pip and Ruby:
- https://github.com/elnappo/dotfiles/blob/master/ansible/vars
