### ISSUE TITLE
[bug] Included profile from imported variable doesn't carry over profile variables

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#246]
Dotdrop version (and git commit if run from source): f1ce2eb (latest master at the time of writing)
Using dotdrop: as a subtree

---

Hello again :smiley: 

This time I'm reporting a crash with dotfiles installation.

So, here we have the main config file
```yaml
# main,yaml
config:
  import_configs:
  - subconfig.yaml
profiles:
  top-profile:
    include:
    - sub-profile
```
And this is the subconfig imported:
```yaml
# subconfig.yaml
dotfiles:
  git_config:
    src: config/git/config
    dst: '{{@@ config_dst @@}}'
profiles:
  sub-profile:
    dotfiles:
      - git_config
    dynvariables:
      config_dst: 'echo $CONFIG_DST'
```
The main ingredients to notice are:
- The included profile is defined in another config file
- The dotfile to install from the included profile depends on a profile variable defined for the included profile

This makes dotdrop crash, or at least misbehave, when trying to install `top-profile`. Indeed, the dotfile from the imported profile (here `git_config`) has an empty `dst`, since the profile variable (`config_dst`) is not carried over to `top-profile`.

---

I tried to fix it myself, but I don't really know which direction to go. The problem seems to be with `CfgYaml.__init__`. Indeed, included variables are resolved early when calling `_merge_variables`, before external config files are loaded, and their profiles parsed. This comment made me think that the situation is more delicate than I thought:
> &#x23; since dotfiles and actions are resolved here
  &#x23; and **variables have been already done** at the beginning
  &#x23; of the parsing, we can clear these include
