### ISSUE TITLE
[bug] Dynamic dotfile path not carried over with included profile

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#250]
Dotdrop version (and git commit if run from source): 5b2b05d
Using dotdrop: as a subtree

This is a continuation of #246. Again, dotfiles are not installed correctly, neither they are corectly displayed with the `files` command.
 
Same scenario as before, dotfile with dynamic `dst` containing a profile variable. The profile is included from another config file. Here the YAML, as a reminder:
```yaml
# main,yaml
config:
  import_configs:
  - subconfig.yaml
profiles:
  top-profile:
    include:
    - sub-profile
```
And this is the subconfig imported:
```yaml
# subconfig.yaml
dotfiles:
  git_config:
    src: config/git/config
    dst: '{{@@ config_dst @@}}'
profiles:
  sub-profile:
    dotfiles:
      - git_config
    dynvariables:
      config_dst: 'echo $CONFIG_DST'
```
---
This time the bug is in my PR #249. 

As I said there, profile dynamic variables are only executed for the current profile, the one passed via the CLI option. This means that for `import`ed config files, dynamic profile variables are not available during parsing, as they haven't been expanded yet.  
This is ok for dynamic variables used in the *content* of a dotfile, since they are expanded *after* the YAML config file is parsed. But dynamic variables used as paths are needed *during* parsing, hence the bug.

Now, I tried to PR, but I want your opinion here. I don't really know when dynamic variables (either profile or not) are meant to be expanded in `include`d profiles. Should they be expanded *before* or *after* inclusion? For `import`ed config files I guess it's before import, but if you could confirm that it would be great

**Comment by deadc0de6** [comment]
I had fear to get to this.  It's an issue for `import/include` profile but goes also beyond. The biggest problem is the fact that import keys (`import_actions`, `import_configs`, `import_variables`, profile's `import`, profile's `include`) allow templating and thus dynamic variables (and variables) must be processed before evaluation those entries. 

Therefore we enter some kind of loop:

* dynvariables in the config file used in one of the import keys need to be evaluating first
* import keys are templated and files are included/imported
* imported elements (especially dynamic variables) are evaluated
* and then any entries (potentially dynvariables) in the *importing* config file should be theoretically re-evaluated to substitute the new variables (potentially dynvariables)
* continue with the next *imported* element

If config elements in the *importing* config file are using dynvariables defined in the *imported* config, we have potentially a problem.

I see multiple ways to solve that but none seem optimal to me:

* all variables/dynvariables used in config entries must be available in the same config file (as well as included profile should be defined in the same config file)
* templating is not allowed in any import keys
* reduce or refactor the way import is done: only allow `import_configs` and disallow the use of templating in this entry. That would allow us to merge all configs in one and then process with the evaluation of all variables (much cleaner)
* processing config elements multiple times until no substitution need to be done (before `import` for example, but again after `import` to make sure imported variables/dynvariables can be substituted in any element using them in the config)

They don't all fix the issues but you see the problem. If you have any suggestion, please share. I like the idea of disallowing the use of templating in any *import* keys as this would allow us to have a much cleaner way of parsing. But this could break some people configs too, what is definitely not optimal.

**Comment by davla** [comment]
I understand the problem, and I was starting to realize that a while back.

I do have a suggestion, which is to have well-defined "(profile) (dyn)variables parsing/expansion stages". Something like:

| Where to expand | What to add | Available variables |
-|-|-
| 1- `(dyn)variables` in the same YAML config file | Variables defined in the same file | <ul><li>Variables previously expanded in this stage</li></ul> |
| 2- Entries in `import_variables` | Variables from imported variable files | <ul><li>Variables defined in the same YAML config files</li><li>Variables previously expanded in this stage</li></ul> |
| 3- Entries in `import_configs` | Variables from imported config files | <ul><li>Variables defined in imported variable files</li><li>Variables defined in the same YAML config files</li><li>Variables previously expanded in this stage</li></ul> |
| 4- All the rest | Nothing is left, isn't it? | All the variables: <ul><li>Variables defined in imported variable files</li><li>Variables defined in the same YAML config files</li><li>Variables previously expanded in this stage</li></ul> |

Further notes/explanations:
* Every stage has available all the variables added in previous stages and the ones already expanded in this stage.
* Profile variables always override global variables with the same name.
* Config files do not have available variables defined *above* in the include tree.
* Dynvariables are executed in the same stage they are expanded.

**Comment by deadc0de6** [comment]
Yes the systematic approach is really good. 

So we would need to first process all dynvariables/variables in all included elements before the rest (to make sure everything can be expanded/templated). Also this would mean we'd have some *postponed* dynvariables/variables in case they use variables that are not yet defined. Those would need to be processed after insertion of new variables until nothing left is *undefined*.

**Comment by deadc0de6** [comment]
I changed the way the templating works. Now undefined variables being used in templates or config entries will raise an exception. This will allow us to more precisely control the parsing of variables/dynvariables, that is which one is to be postponed for later re-evaluation.

Also this would give a better control to the user on the content (and being warned when anything is undefined).

**Comment by davla** [comment]
Anything I can help with?

**Comment by deadc0de6** [comment]
Thanks a lot @davla, I'll try to refactor the way config parsing is being done and will integrate your suggestions. I'd be thankful if you could test it ultimately as I know you have some very interesting uses in your config files. If you have any other suggestions, feel free to drop them here of course.

**Comment by deadc0de6** [comment]
@davla I think I have something in the [bug250 branch](https://github.com/deadc0de6/dotdrop/tree/bug250). I implemented some more tests and will document the different rules on the wiki as soon as this is merged into the master branch.  Would you like to test it as I know you have some complex config files and that would help me veritfy everything is indeed working as intended.

**Comment by davla** [comment]
I will asap. Thanks again for working on this.

**Comment by davla** [comment]
Sorry for the late reply :sweat_smile: Good job here, it was quite a substantial change :+1: 

Unfortunately, it's not working yet :sob: Here the real-world use case (I did some investigation, scroll past the example):
```yaml
# main.yaml

config:
  import_configs:
  - commands.yaml

dotfiles:
  f_asdf-env-bash:
    src: env/source-asdf-env
    dst: '{{@@ asdf_env_tmp_dst @@}}'

profiles:
  asdf:
    dotfiles:
    - f_asdf-env-bash
    dynvariables:
      asdf_env_tmp_dst: mktemp /tmp/asdf-env-tmp.XXX
  timers:
    include:
    - host-refresh
```
```yaml
# comands.yaml

dotfiles:
  f_hosts:
    src: etc/hosts
    dst: '{{@@ hosts_tmp_dst @@}}'

profiles:
  host-refresh:
    dotfiles:
    - f_hosts
    dynvariables:
      hosts_tmp_dst: mktemp /tmp/hosts-append.XXX
```
So, the following command exits with an error on `hosts_tmp_dst`:
```bash
bash dotdrop.sh -c config-root.yaml files -p timers
[ERR] config error: 'hosts_tmp_dst' is undefined
```
If I try to use the profile that actually defines the `hosts_tmp_dst` variable:
```bash
bash dotdrop.sh -c config-root.yaml files -p host-refresh
[ERR] config error: 'asdf_env_tmp_dst' is undefined
```
So, I last tried with the profile that defines `asdf_env_tmp_dst`, that does not even remotely involve `hosts_tmp_dst`
```bash
bash dotdrop.sh -c config-root.yaml files -p asdf
[ERR] config error: 'hosts_tmp_dst' is undefined
```
---
So, the problem seems to be related to profile (dyn)variables of profiles other than the current one. I had the suspicion that
dotfile entries' `dst` and `src`are always resolved, regardless of whether the dotfile is part of the current profile or not. However, this clashes with the new implementation, that only adds profile variables from the current profile.  
In fact, if a dotfile, that is not included in the current profile, uses a variable defined only by a profile that actually includes it, and not by the current profile, the variable will be undefined, and an `UndefinedException` is raised.

I added this ugly snippet to prove my suspicion:
```diff
diff --git a/dotdrop/dotdrop/cfg_yaml.py b/dotdrop/dotdrop/cfg_yaml.py
index df31162..2d1a8f0 100644
--- a/dotdrop/dotdrop/cfg_yaml.py
+++ b/dotdrop/dotdrop/cfg_yaml.py
@@ -249,8 +249,21 @@ class CfgYaml:
         newdst = ''
         if dst:
             new = dst
-            if templater:
-                new = templater.generate_string(dst)
+            had_exceptions = True
+            while had_exceptions:
+                try:
+                    if templater:
+                        new = templater.generate_string(dst)
+                        had_exceptions = False
+                except UndefinedException:
+                    pro_var = self._get_profile_included_item(self.key_profile_variables, self.profiles.keys())
+                    pro_dvar = self._get_profile_included_item(self.key_profile_dvariables, self.profiles.keys())
+                    self._add_variables(new=pro_var, prio=True)
+                    self._add_variables(new=pro_dvar, prio=True, shell=True)
+
+                    templater = Templategen(variables=self.variables)
+                    had_exceptions = True
+
             if new != dst and self._debug:
                 msg = 'dotfile dst: \"{}\" -> \"{}\"'.format(dst, new)
                 self._dbg(msg)
@@ -612,9 +625,9 @@ class CfgYaml:
         variables['_dotdrop_workdir'] = p
         return variables

-    def _get_profile_included_item(self, keyitem):
+    def _get_profile_included_item(self, keyitem, profiles=None):
         """recursively get included <keyitem> in profile"""
-        profiles = [self._profile] + self._inc_profiles
+        profiles = profiles or [self._profile] + self._inc_profiles
         items = {}
         for profile in profiles:
             seen = [self._profile]
```
Shortly, here I add the variables from ALL the profiles in case the templating fails with an `UndefinedException` when resolving a dotfile's `dst`.  
It's definitely not a good solution, and it probably creates problems in many other places, but it does work. The commands in the previous section now produce the expected output :smile: 

---
I have a couple of suggestion on how to solve this problem:
1. Only resolve the current profile dotfiles' `dst` and `src` (aka lazy dotfiles loading). This way, if a dotfile, that is not included in the current profile, uses a variable from another profile, it doesn't matter, since we're not going to resolve its `dst` and `src`.
2. This is flakier, but we could just ignore undefined variables if they are defined in another profile. This would require: computing a list of all the profile (dyn)variable names (without values); adding the variable name as an attribute on `UndefinedException` from the underlying `UndefinedError`; matching the variable name in the `UndefinedException` agains the profile (dyn)variable names list. If a match is found, then we ignore the exception. As I said before, this is quite flakier compared to the previous option, and probably it requires as much work. I wouldn't go for this.

**Comment by deadc0de6** [comment]
Good catch thanks! I went for your solution (1) since it made more sense. I've added a test for this and also implemented selective dotfiles paths templating (only for the selected profile and included ones).

**Comment by deadc0de6** [comment]
@davla while merging your PR (#252) I noticed a new issue: both `variables` and `dynvariables` must be able to cross-reference however we then have to choose as to whether templating them first or executing dynvariables first.

Both solutions have their pros/cons but I chose to go with the `templating first`. See below for an overview of the two different outputs for these solutions. I'm open to discussing it if you think the other solution is better.

## templating first

This will result with `dvar0 = "test"` and `var0 = "echo test"` (**not** `var0 = test`)
```yaml
variables:
  var0: "{{@@ dvar0 @@}}"
dynvariables:
  dvar0: "echo test"
```

This will result with `dvar0 = "test"` and `var0 = "test"`
```yaml
variables:
  var0: "test"
dynvariables:
  dvar0: "echo {{@@ var0 @@}}"
```

## executing first

This will result with `dvar0 = "test"` and `var0 = "test"`
```yaml
variables:
  var0: "{{@@ dvar0 @@}}"
dynvariables:
  dvar0: "echo test"
```

This will result with `dvar0 = "{{@@ var0 @@}}"`  (and **not** `dvar0 = "test"`) and `var0 = "test"`
```yaml
variables:
  var0: "test"
dynvariables:
  dvar0: "echo {{@@ var0 @@}}"
```

**Comment by davla** [comment]
I agree that we should go for *templating first*. Non-dynamic variables can be used to bootstrap the whole setup, allowing dynamic variables to take advantage of them. And in case a more dynamic setup is needed, environment variables can be accessed via templating. This looks like a good compromise between ease of use and flexibility

Just as a reminder, assume that there's something not yet working until I say so. I always try to investigate when I find a bug, so it takes me some time :sweat_smile:

**Comment by deadc0de6** [comment]
Sure take your time, I'll merge when we are sure it's stable.
Thanks again for your help.

**Comment by davla** [comment]
Another problem, this time with templating in dotfiles content. I didn't check my setup, but I assume that all variables, regardless of how they're declared/imported should be available when templating a dotfile's content. I tried to investigate, but I could get nothing out of this. Hence, I'm reporting the part of my setup that I feel is relevant

---

So, basically I have a top-level config that imports another config, that imports a variables file. Then, the dotfiles using the variables in their content are defined in the top-level config file.
```yaml
# config.yaml (top-level)

config:
  import_configs:
  - yaml/profiles/shared.yaml

dotfiles:
  f_gtk-3.0_settings.ini.lodpi:
    src: config/gtk-3.0/settings.ini.lodpi
    dst: '~/.config/gtk-3.0/settings.ini.lodpi'

```
```yaml
# shared.yaml (sub-config)

config:
  import_variables:
  - ../variables/look-and-feel.yaml
```
```yaml
# variables/look-and-feel.yaml (variables file)

variables:
  cursor_size: 24
  font: Sans, Regular 11
  theme: Adwaita-dark
```
```ini
# config/gtk-3.0/settings.ini.lodpi
[Settings]
gtk-application-prefer-dark-theme = true
gtk-cursor-theme-size = {{@@ cursor_size @@}}
gtk-font-name = {{@@ font @@}}
gtk-theme-name = {{@@ theme @@}}
```

**Comment by deadc0de6** [comment]
Yes all variables are available for dotfile's content templating.

I created [this test-case](https://github.com/deadc0de6/dotdrop/commit/546e13b4a6ea657064b7884ded039e6fc5b19605) but wasn't able to reproduce your issue.

Can you provide me with more information (debug logs or the relevant lines).  Also you can always test the above test-case on your side to see if anything different comes up.

**Comment by davla** [comment]
I can also work directly on the test case, and add the missing pieces that make it fail. I'm quite sure there are some details I overlooked in my setup that actually cause the issue.

**Comment by davla** [comment]
I found the culprit. It was a jinja macro. I didn't include it in the example as I didn't think it was relevant. The imports and the variable parsing works fine :+1: Below, a much more stripped-down example that will reproduce the bug:

```yaml
# config.yaml

dotfiles:
- f_with-macro:
  dst: abc
  src: abc

variables:
  local: local
  global: global 
```
```html+jinja
# abc
{%@@ from 'macros_file' import macro @@%}
{{@@ macro(local) @@}}
```
```html+jinja
# macros_file
{%@@ macro(var) @@%}
{{@@ var @@}}
{{@@ global @@}}
{%@@ endmacro @@%}
```

---

So, the "bug" is caused by the fact that the macro accesses a "global" variable, that is one which is not passed as an argument. It worked before e3b7359, as variables were added to `Environment.globals` in `Templategen`. After that commit, variables are passed in as an argument to `Template.render`, meaning that they are not globals anymore. As a result, jinja cannot find the variable in templated files when they are `import`ed, which is often the case when you define a jinja macro in a separate file.

---

Nonetheless, I'm happier with the current implementation. It's closer to the standard jinja uses, like in Flask. And the fix is really straightforward to, just add `with context` to the import statement, like this
```html+jinja
{%@@ from 'macro_file' import macro with context @@%}
```
However, this is a backwards-incompatible change. If you want to keep it, make sure you mention it in the documentation and the changelog, and don't forget remove the test case you created. If you want to restore the previous behavior, the example is in #253 :smile:
