### ISSUE TITLE
[feature] allow for (secrets) transformation of directories

### ISSUE THREAD

**Issue by 5nafu** [deadc0de6/dotdrop#251]
As a user I would like to transform/encrypt multiple files in a config.d directory without needing to add them individually to dotdrop.

I have a config directory `config.d` (for example `.ssh/config.d/` or `.kube/config.d/`) with multiple files. I can add those with just one configuration to `dotdrop`:
```
dotfiles:
  d_kubeconfig:
    dst: ~/.kube/config.d
    src: kube_config.d
```
Unfortunately, when there are secret information in the files, I can not use the transform action currently stated in the wiki:
```
trans_write:
  gpg: gpg -qaer {{@@ KEYID @@}} -o- {0} > {1}
trans_read:
  gpg: gpg -q --for-your-eyes-only --no-tty -d {0} > {1}
```
as `{1}` will be a file and the transformation is called once per config-entry (in this case a directory).

If `dotdrop` would detect the `src`/`dst` being a directory and therefor setting up `{1}` as a tempdir and calling the transform script for each file, an encrypt/decrypt would be possible.

An alternative would be to encrypt a tar file and use a post action to put all files to the desired destination, but this would be difficult to maintain, as the `dst`-tarfile will not change when the real files are modified and a `dotdrop compare` will not pick up the changes.

**Comment by 5nafu** [comment]
It appears that this is possible with using a tar file together with encryption as the temporary file is _not_ created automatically.

One can use the following setup to achieve this:
```
dotfiles:
  d_kubeconfig:
    dst: ~/.kube/config.d
    src: kube_config.d
    trans_read: gpgdir
    trans_write: gpgdir
trans_write:
  gpgdir: tar -c -C {0} . | gpg -qaer {{@@ KEYID @@}} -o {1}
trans_read:
  gpgdir: mkdir {1} && gpg -q --for-your-eyes-only --no-tty -d {0} |tar -x -C {1}
```

Sorry for the noise.
