### ISSUE TITLE
[feature] supress verbose of "dotfile does not exist in dotdrop"

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#255]
## Situation

I have below setting in config.yaml:

```
  d_quickphrase.d:
    src: local/share/fcitx5/data/quickphrase.d
    dst: ~/.local/share/fcitx5/data/quickphrase.d
    link: link_children
```

And in directory `quickphrase.d` all files are symbolic link managed by dotdrop, except one symbolic link created by me point to a file which managed by cloud driver application.

So each time I use `dotdrop compare` it shows a info saying that file is not managed by dotdrop:

```
=> compare d_quickphrase.d: diffing with "/home/roach/.local/share/fcitx5/data/quickphrase.d"
=> "password.mb" does not exist in dotdrop
```

But, as I use `link_children` means I agree with no all files managed by dotdrop under `quickphrase.d`? I will use `link: link` directly, otherwise.

## Expected

In my mind, dotdrop should supress the info says which file not managed by dotdrop under a directly if the link attribute is `link_children`.

Thanks in advance!

**Comment by deadc0de6** [comment]
Dotdrop will still notify you that there's a file in the directory that it doesn't know about. It makes sense since from dotdrop perspective the entire directory is managed, not all single files/directories under it. Also there might be other use-cases when you'd like to be notified when the managed directories is different on the filesystem as what you have in dotdrop (be it with `link_children` or otherwise).

You can of course make use of `cmpignore` and `upignore` to avoid the notification (for more see [this page](https://github.com/deadc0de6/dotdrop/wiki/ignore-pattern)):
```yaml
  d_quickphrase.d:
    src: local/share/fcitx5/data/quickphrase.d
    dst: ~/.local/share/fcitx5/data/quickphrase.d
    link: link_children
    cmpignore:
    - "*password.mb*"
    upignore:
    - "*password.mb*"
```
