### ISSUE TITLE
Managing the same dotfile location but for different profiles

### ISSUE THREAD

**Issue by smac89** [deadc0de6/dotdrop#26]
I find myself doing the following in config.yml

```yml
dotfiles:
  f_zshrc_host1:
    dst: ~/.zshrc
    src: zshrc_host1
  f_zshrc_host2:
    dst: ~/.zshrc
    src: zshrc_host2
profiles:
  host1:
    dotfiles:
    - f_zshrc_host1
  host2:
    dotfiles:
    - f_zshrc_host2
```

So in essence, I wanted to manage the same location for my `.zshrc`, but for different hosts and by extension different configurations.

When I did `dotdrop import -p host1 ~/.zshrc`, it creates a dotfile with the name `zshrc`. Then when I did the same for my other host (`dotdrop import -p host2 ~/.zshrc`), it will simply default to sharing that file for both hosts. This is not what I want.

To accomplish what I wanted, I have created separate files for both hosts and changed the config accordingly. Am I missing a command for doing this, or do I have to do this manually each time? I feel like this should be part of the basic functionality.

I have no problem doing it manually seeing as it still works when I install the files, but I was wondering if I am missing a built-in way for doing this.

Thanks
