### ISSUE TITLE
[help] Possible to symlink on *nix and copy on window machines?

### ISSUE THREAD

**Issue by Lilja** [deadc0de6/dotdrop#268]
Let's say I have two hosts, a ubuntu server and a windows machine. On the windows machine, I'm using [git bash](https://git-scm.com/downloads). Using git bash, the `ln -s` to symlink files is quite limited and doesn't work without figuring out a lot of admin rights and editing stuff in windows that I really don't want to deal with. So as a good compromise I think it would be good to just copy the files over to the target directory, while using more proper *nix systems it would just symlink it as usual.

Is it possible to configure this using dotdrop?

**Comment by deadc0de6** [comment]
Yes it's possible. What I would suggest is to keep only one file in the *dotpath* but two entries in the config file pointing to the same file.

For example
```yaml
dotfiles:
  f_test:
    src: test
    dst: ~/.test
  f_test_symlink:
    src: test
    dst: ~/.test
    link: link
profiles:
  linux:
    dotfiles:
    - f_test_symlink
  windows:
    dotfiles:
    - f_test
```

```bash
$ tree dotfiles          
dotfiles
└── test
```

Since both hosts are matched into a different profile you can install the dotfile independently on each side:
```bash
$ ./dotdrop.sh install --profile windows
	-> copied /home/user/dotdrop/dotfiles/test to /home/user/.test
$ /dotdrop.sh install --profile linux  
	-> linked /home/user/.test to /home/user/dotdrop/dotfiles/test
```

The `dst` part could of course be adapted but as long as you keep the same `src`, both dotfile entry will point to the same file.

**Comment by Lilja** [comment]
Thanks! So the solution would be to duplicate them and use include/exclude for the different profiles, I see. It's less ideal than I would thought, as I would think if I needed a lot of dotfiles I wouldn't have to duplicate them. 

But I think it's managable since I only need vim config files on windows.

**Comment by deadc0de6** [comment]
Well the thing is that the `link` attribute can currently not be templated in the config.
I'll see how that could work but one solution would be to allow something like this
```yaml
variables:
  link_value: "nolink"
dotfiles:
  f_test:
    src: test
    dst: ~/.test
    link: "{{@@ link_value @@}}"
profiles:
  linux:
    dotfiles:
    - f_test
    variables:
      link_value: "link"
  windows:
    dotfiles:
    - f_test
```

You only have one dotfile and its link entry is dependent on the `link_value` variable that can be changed at will.

**Comment by Lilja** [comment]
Interesting! I'll get to try that when I get more familiar. For now, I'm having some trouble with running `install`:

```
$ dotdrop.exe -V install --profile windows --cfg config.yaml
[DEBUG][dotdrop.options.__init__] version: 1.2.1
[DEBUG][dotdrop.options.__init__] command: C:\Users\Erik Lilja\AppData\Local\Programs\Python\Python36-32\Scripts\dotdrop -V install --profile windows --cfg config.yaml
[DEBUG][dotdrop.options.__init__] config file: config.yaml
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] ----------start:C:\Users\Erik Lilja\dotfiles\config.yaml----------
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml]
actions:
  pre:
    vim-plug-install: test -e ~/.vim/autoload/plug.vim || (mkdir -p $XDG_CONFIG_HOME/vim/autoload; curl
      -fLo $XDG_CONFIG_HOME/vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
    vim-plug: vim +PlugInstall +qall

dotfiles:
  vim_windows:
    src: vim
    dst: ~/.vim
    actions:
       - vim-plug-install
       - vim-plug
  vim_rc_windows:
    src: vim/vimrc
    dst: ~/.vimrc
    actions:
       - vim-plug-install
       - vim-plug
  vim:
    src: vim
    dst: "{{@@ env['XDG_CONFIG_HOME'] @@}}/vim"
    link: link
    actions:
       - vim-plug-install
       - vim-plug
  fish:
    src: fish
    dst: "{{@@ env['XDG_CONFIG_HOME'] @@}}/fish"
    link: link
  git:
    src: git
    dst: "{{@@ env['XDG_CONFIG_HOME'] @@}}/git"
    link: link
  tmux_conf:
    src: tmux
    dst: "{{@@ env['XDG_CONFIG_HOME'] @@}}/tmux"

profiles:
  nix:
    dotfiles:
    - vim
    - fish
    - git
  windows:
    dotfiles:
    - vim_windows
    - vim_rc_windows
[DEBUG][dotdrop.cfg_yaml._dbg] [config.yaml] ----------end:C:\Users\Erik Lilja\dotfiles\config.yaml----------
[ERR] config error: invalid config: no config found

```

do you have any clue what I'm doing wrong here? dotdrop has parsed my file but it says it can't find my config 🤔

**Comment by deadc0de6** [comment]
It's misleading since it's the yaml parser who says `no config found` and that's because you have no `config` entry in your config file.

You are missing this:
```yaml
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
```

You can find more info in the [doc](https://dotdrop.readthedocs.io/en/latest/config-format/)
