### ISSUE TITLE
[help] failed to make a post-action: remove last three line

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#272]
**What I am trying to achieve**

I wanna remove last three lines of an entry in config.yaml.

**What I have tried so far**

I had add below action to config.yaml:

```
actions:
  post:
    remove-last-three-lines: sed -i "$(($(wc -l < {{@@ _dotfile_abs_dst @@}})-2)),\$d" {{@@ _dotfile_abs_dst @@}}
...
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
    actions:
      - remove-last-three-lines
```

**The problem is:**

After I run `dotdrop install`, `dotdrop compare` says still have difference:

```
hmanx ~/./p/vim-anzu master » dpcp
=> compare f_vimrc: diffing with "/home/roach/.vimrc"
--- /home/roach/.vimrc  2020-10-13 22:19:44.833002808 +0800
+++ /tmp/dotdrop-ipbd4mxm/home/roach/.vimrc     2020-10-13 22:21:13.553007402 +0800
@@ -2121,3 +2121,6 @@
 " Plug 'roachsinai/vim-barbaric'
 " let g:barbaric_scope = 'buffer'
 " key code delay https://www.johnhawthorn.com/2012/09/vi-escape-delays/
+
+==============================================================================
+vim:fdm=marker
```

And can still run a `dotdrop install` (means I can run install again and again):

```
hmanx ~/./p/vim-anzu master » dpin
Overwrite "/home/roach/.vimrc" [y/N] ? y
backup /home/roach/.vimrc to /home/roach/.vimrc.dotdropbak
        -> copied /home/roach/code/Git/dotfiles/dotfiles/vimrc to /home/roach/.vimrc
        -> executing "sed -i "$(($(wc -l < /home/roach/.vimrc)-2)),\$d" /home/roach/.vimrc"

1 dotfile(s) installed.
```

Is there a way to let dordrop know there is no difference? Thanks in advance!
