### ISSUE TITLE
[help] Post vs Pre action depending on the dotfile ?

### ISSUE THREAD

**Issue by vikigenius** [deadc0de6/dotdrop#278]
I am new to using dotdrop and I was reading the examples.
One thing is not very clear. When you say there are two types of action pre and post, are they specific to the action itself or for the dotfile?

For eg:

```
actions:
  pre:
    action1: 'some_action {0}'
dotfiles
  d_dotfile1:
    src: some_src
    dst: some_dst
    actions:
      - action1 arg1
  d_dotfile2:
    src: some_src
    dst: some_dst
    actions:
      - action1 arg2
```

Does this mean that for both dotfile1 and dotfile2 action1 is a pre action?
What if I am in a situation where I want action1 to be run as a pre action for dotfile1 and as post action for dotfile2 ?

Something like the following:

```
actions:
  action1: 'some_action {0}'
dotfiles
  d_dotfile1:
    src: some_src
    dst: some_dst
    actions:
      pre:
        - action1 arg1
  d_dotfile2:
    src: some_src
    dst: some_dst
    actions:
      post:  
        - action1 arg2
```

Is this possible ?

**Comment by deadc0de6** [comment]
The `pre`/`post` keywords are specific to the action itself (see the [config format doc](https://dotdrop.readthedocs.io/en/latest/config-format/)).
No you can't have the same action being `pre` and `post` but you can have so called *dynamic* actions to avoid too much redundancy (see [this doc](https://dotdrop.readthedocs.io/en/latest/config-details/#dynamic-actions)). For example

```yaml
actions:
  pre:
    action1_pre: "{{@@ action1 @@}} {0}"
  post:
    action1_post: "{{@@ action1 @@}} {0}"
variables:
  action1: "echo test >"
dotfiles:
  d_dotfile1:
    src: some_src
    dst: some_dst
    actions:
    - action1_pre arg1
  d_dotfile2:
    src: some_src
    dst: some_dst
    actions: 
     - action1_post arg2
```
