### ISSUE TITLE
Symlink function on macos broken

### ISSUE THREAD

**Issue by lyze237** [deadc0de6/dotdrop#28]
When I set a file or folder to use links like this:
```
f_config.fish:
     dst: ~/.config/fish/config.fish
     src: config/fish/config.fish
     link: true
```
And I install it normally `./dotdrop.sh --profile=mac`

It generates a symlink to `./dotfiles/config/fish/config.sh` instead of the actual path `<DotfilesFolder>/dotfiles/config/fish/config.sh`
