### ISSUE TITLE
[bug] variable of included profile takes precedence over current profile variable

### ISSUE THREAD

**Issue by otijhuis** [deadc0de6/dotdrop#285]
Dotdrop version (and git commit if run from source): v1.3.6
Using dotdrop: from aur

**Describe the bug**

I have a default arch profile with certain variables set regarding hidpi scaling. 
Another machine specific profile includes that arch profile and sets those variables to different values.
This used to work but those modified values are ignored now and instead it uses the values of the included arch profile.
If I remove the variables from the included arch profile then the expected values are used.

**Steps to Reproduce**

1. Create a dotfile with a profile containing variables
2. Create another profile including the first profile that overrides the same variables
3. When using the variables it uses the values of the included profile, not the values of the profile being installed

**Expected behavior**

I expect the variables of the profile being installed to take precedence over the variables of included profiles.

**Additional information**

The relevant part of the config file
```yaml
profiles:
  arch:
    include:
    - git
    - filemanagement
    - clipboard
    - editor
    - windowmanager
    - tmux
    - terminal
    - shell
    - search
    - video
    - notifications
    - launcher
    - tasks
    - menubar
    - mouse
    - irc
    - fonts
    variables:
      dpi: 96
      gdk_dpi_scale: 1
      gdk_scale: 1
      qt_auto_screen_scale_factor: 1
      qt_screen_scale_factors: 1
      rofi_font_size: 15
      term_font_size: 20
  nuc:
    include:
    - arch
    - sound
    variables:
      cursor_size: 16
      dpi: 192
      gdk_dpi_scale: 1
      gdk_scale: 1
      qt_auto_screen_scale_factor: 1
      qt_screen_scale_factors: 0.9
      rofi_font_size: 24
      term_font_size: 15
      sound_device: 3
      mouse_scroll_speed: 2
```
