### ISSUE TITLE
[help]How to link same file to different destination on different machines?

### ISSUE THREAD

**Issue by liebkne** [deadc0de6/dotdrop#297]
**What I am trying to achieve**

I'd like to link `f_something` to `~/.config/` on Ubuntu and `~/Library` on Mac.

**What I have tried so far**

Used [profile-variables](https://dotdrop.readthedocs.io/en/latest/howto/sharing-content/#profile-variables) to define a dir variable and put a `variables` section under every profile.

My question is: Is there a simpler way to do this? Since I have one Mac and many Ubuntus and I have to put the same variable under all Ubuntu profiles.

**Comment by deadc0de6** [comment]
You can do it like this
```yaml
dotfiles:
  f_something_ubuntu:
    dst: ~/.config/something
    src: config/something
  f_something_mac:
    dst: ~/Library/something
    src: config/something
profiles:
  ubuntu:
    dotfiles:
    - f_something_ubuntu
  mac:
    dotfiles:
    - f_something_mac
```

both `f_something_ubuntu` and `f_something_mac` points on the same file in dotdrop *dotpath* directory but are handled as two different dotfiles.

Or like that (see [this doc](https://dotdrop.readthedocs.io/en/latest/config-details/#dynamic-dotfile-paths))
```yaml
variables:
  something_dst: "~/.config/something"
dotfiles:
  f_something:
    dst: "{{@@ something_dst @@}}"
    src: config/something
profiles:
  ubuntu:
    dotfiles:
    - f_something
  mac:
    dotfiles:
    - f_something
    variables:
      something_dst: "~/Library/something"
```
