### ISSUE TITLE
[help]Download and link a script

### ISSUE THREAD

**Issue by Yevgnen** [deadc0de6/dotdrop#299]
**What I am trying to achieve**

I'd like to download the `cht.sh` script (following [this](https://github.com/chubin/cheat.sh#installation)) and put it to `~/dotfiles/dotfiles/bin/cht.sh` and link it to `~/bin/cht.sh` so that I can use the latest upstream version of `cht.sh` every time when I install using `dotdrop`.

**What I have tried so far**
I have something like 

```yaml
actions:
  pre:
    prepare_cht.sh: "curl https://cht.sh/:cht.sh > {{@@ _dotfile_abs_src @@}}/cht.sh"

```
and 

```
dotfiles:
  d_bin:
    src: bin
    dst: ~/bin
    link: link_children
    chmod: 700
    actions:
      - prepare_cht.sh
```

in my `config.yaml`.

The `cht.sh` script is actually downloaded when install and all the other scripts under `bin` are linked except the downloaded one.

Also tried 

```
dotfiles:
  d_bin:
    src: bin
    dst: ~/bin
    link: link_children
    chmod: 700
    actions:
      pre: # add this
        - prepare_cht.sh
```

but got syntax error.
