### ISSUE TITLE
[help]  ignored  message

### ISSUE THREAD

**Issue by yuceltoluyag** [deadc0de6/dotdrop#307]
version v1.5.3
When I make changes to these files, these warning messages appear
am I doing something wrong?
```
[WARN] "/home/friday13/.config/polybar" ignored 
[WARN] "/home/friday13/.config/systemd" ignored 
[WARN] "/home/friday13/.config/polybar" ignored 
[WARN] "/home/friday13/.config/libfm" ignored 
[WARN] "/home/friday13/.config/pcmanfm" ignored 
[WARN] "/home/friday13/.config/files" ignored 
[WARN] "/home/friday13/.config/sxiv" ignored 
[WARN] "/home/friday13/.config/alacritty" ignored 
[WARN] "/home/friday13/.config/cava" ignored 
[WARN] "/home/friday13/.config/feh" ignored 
[WARN] "/home/friday13/.config/getkeys" ignored 
[WARN] "/home/friday13/.config/htop" ignored 
[WARN] "/home/friday13/.config/i3" ignored 
[WARN] "/home/friday13/.config/i3status" ignored 
[WARN] "/home/friday13/.config/mpv" ignored 
[WARN] "/home/friday13/.config/nano" ignored 
[WARN] "/home/friday13/.config/neofetch" ignored 
```
config.yaml

```
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_xdefaults:
    src: Xdefaults
    dst: ~/.Xdefaults
  f_nvidia-settings-rc:
    src: nvidia-settings-rc
    dst: ~/.nvidia-settings-rc
  f_lock.png:
    src: lock.png
    dst: ~/.lock.png
  f_imwheelrc:
    src: imwheelrc
    dst: ~/.imwheelrc
  f_gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_face:
    src: face
    dst: ~/.face
  f_dircolors:
    src: dircolors
    dst: ~/.dircolors
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_amrc:
    src: amrc
    dst: ~/.amrc
  f_alarm.wav:
    src: alarm.wav
    dst: ~/.alarm.wav
  d_weechat:
    src: weechat
    dst: ~/.weechat
    chmod: '700'
  d_urxvt:
    src: urxvt
    dst: ~/.urxvt
    chmod: '700'
  d_script:
    src: script
    dst: ~/.script
    chmod: '711'
  d_pacbac:
    src: pacbac
    dst: ~/.pacbac
  d_git_template:
    src: git_template
    dst: ~/.git_template
  d_gnupg:
    src: gnupg
    dst: ~/.gnupg
    chmod: '700'
  d_colors:
    src: colors
    dst: ~/.colors
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_tmux.conf.osx:
    src: tmux.conf.osx
    dst: ~/.tmux.conf.osx
  f_tmux.powerline.conf:
    src: tmux.powerline.conf
    dst: ~/.tmux.powerline.conf
  f_dmrc:
    src: dmrc
    dst: ~/.dmrc
  f_xscreensaver:
    src: xscreensaver
    dst: ~/.xscreensaver
  f_fzf.bash:
    src: fzf.bash
    dst: ~/.fzf.bash
  f_fzf.zsh:
    src: fzf.zsh
    dst: ~/.fzf.zsh
  f_fehbg:
    src: fehbg
    dst: ~/.fehbg
    chmod: '754'
  f_xauthority:
    src: Xauthority
    dst: ~/.Xauthority
    chmod: '600'
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_systemd:
    src: config/systemd
    dst: ~/.config/systemd
  d_libfm:
    src: config/libfm
    dst: ~/.config/libfm
    chmod: '700'
  d_pcmanfm:
    src: config/pcmanfm
    dst: ~/.config/pcmanfm
    chmod: '700'
  d_files:
    src: config/files
    dst: ~/.config/files
  d_sxiv:
    src: config/sxiv
    dst: ~/.config/sxiv
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_cava:
    src: config/cava
    dst: ~/.config/cava
  d_feh:
    src: config/feh
    dst: ~/.config/feh
  d_getkeys:
    src: config/getkeys
    dst: ~/.config/getkeys
  d_htop:
    src: config/htop
    dst: ~/.config/htop
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_i3status:
    src: config/i3status
    dst: ~/.config/i3status
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
  d_nano:
    src: config/nano
    dst: ~/.config/nano
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  d_optimus-manager:
    src: config/optimus-manager
    dst: ~/.config/optimus-manager
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_termite:
    src: config/termite
    dst: ~/.config/termite
  d_tmux:
    src: config/tmux
    dst: ~/.config/tmux
  d_tumbler:
    src: config/tumbler
    dst: ~/.config/tumbler
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
  d_wal:
    src: config/wal
    dst: ~/.config/wal
  d_gimp:
    src: config/GIMP
    dst: ~/.config/GIMP
  d_i3menu:
    src: config/i3menu
    dst: ~/.config/i3menu
  d_spicetify:
    src: config/spicetify
    dst: ~/.config/spicetify
    chmod: '700'
  d_ncmpcpp:
    src: config/ncmpcpp
    dst: ~/.config/ncmpcpp
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_xarchiver:
    src: config/xarchiver
    dst: ~/.config/xarchiver
    chmod: '700'
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    chmod: '750'
  d_calcurse:
    src: config/calcurse
    dst: ~/.config/calcurse
  d_betterdiscord:
    src: config/BetterDiscord
    dst: ~/.config/BetterDiscord
  d_wal-discord:
    src: config/wal-discord
    dst: ~/.config/wal-discord
  d_thunar:
    src: config/Thunar
    dst: ~/.config/Thunar
profiles:
  f13:
    dotfiles:
    - f_xinitrc
    - f_xresources
    - f_xprofile
    - f_xmodmap
    - f_xdefaults
    - f_nvidia-settings-rc
    - f_lock.png
    - f_imwheelrc
    - f_gtkrc-2.0
    - f_gitignore
    - f_gitconfig
    - f_face
    - f_dircolors
    - f_bashrc
    - f_bash_profile
    - f_amrc
    - f_alarm.wav
    - d_weechat
    - d_urxvt
    - d_script
    - d_pacbac
    - d_git_template
    - d_gnupg
    - d_colors
    - f_tmux.conf
    - f_tmux.conf.osx
    - f_tmux.powerline.conf
    - f_dmrc
    - f_xscreensaver
    - f_fzf.bash
    - f_fzf.zsh
    - f_fehbg
    - f_xauthority
    - d_polybar
    - d_systemd
    - d_libfm
    - d_pcmanfm
    - d_files
    - d_sxiv
    - d_alacritty
    - d_cava
    - d_feh
    - d_getkeys
    - d_htop
    - d_i3
    - d_i3status
    - d_mpv
    - d_nano
    - d_neofetch
    - d_optimus-manager
    - d_picom
    - d_termite
    - d_tmux
    - d_tumbler
    - d_zathura
    - d_wal
    - d_gimp
    - d_i3menu
    - d_spicetify
    - d_ncmpcpp
    - d_dunst
    - d_rofi
    - d_xarchiver
    - d_ranger
    - d_nvim
    - d_calcurse
    - d_betterdiscord
    - d_wal-discord
    - d_thunar

```
