### ISSUE TITLE
[help] single action run multiple  commands

### ISSUE THREAD

**Issue by Syusyuly** [deadc0de6/dotdrop#309]
**What I am trying to achieve**
Sometimes one command cannot achieve my goal, I have to divide actions into two lines, if not more. How can I define a action including multiple commands.

**What I have tried so far**
```yaml
actions:
  test: command1
        command2
  test: command1 \
        command2
```

**Comment by Syusyuly** [comment]
Well, I figured out that the following form should be okay

```yaml
actions:
  test: command1;
        command2
```
