### ISSUE TITLE
[feature] don't install empty directories

### ISSUE THREAD

**Issue by sadsumi** [deadc0de6/dotdrop#314]
My use case might be too specific to me but, I don't know, someone might find it useful. It's also more of a cosmetic change.

**What I need**

If there's an empty directory managed by dotdrop (either because it's actually empty or it/its content is ignored), I don't want it to be copied when installing, possibly by setting some `ignoreemptydir` option. `dotdrop install` should also never mention it in its output.

**What I've tried**

First of all, I think it's currently not true. If I have an `awesome` directory that is managed by dotdrop, and then some `awesome/empty` directory in it, even though I add `awesome/empty` to `instignore` (as `*empty` as suggested in docs, or as `*empty*`) it's still gonna be copied. Example:

```yaml
  d_awesome:
    dst: ~/.config/awesome
    src: config/awesome
    link: nolink
    ignoreempty: true
    instignore:
    - '*empty'
```

**Use case**

some of my dotfiles are complex, e.g. `awesome`. It consists of a lot of scripts which use templating to manage different profiles. I add those dotfiles to separate git repositories to manage multiple versions of them. Now, I want to add `.git` directory to `instignore` (`*.git*` to also ignore its content) so it will never be copied to the actual machine and won't clutter the output of install command - which is a bit of a hassle. But despite this setting, empty directories are still created (and `git` creates a lot of directories). They also change whenever I commit or do other things.

I might use an action to delete this directory after it's installed but it still clutters the output and ~~forces me to confirm every single empty directory (I don't force my installs)~~

**Comment by deadc0de6** [comment]
The dotfile entry `ignoreempty` applies to templates (as mentioned [in the doc](https://dotdrop.readthedocs.io/en/latest/config-format/#dotfiles-entry)). The reason dotdrop is able to do that is because it will first transform the content (using templating) and then be able to establish that the content is empty and thus ignore the file creation.

Directories (and more generally files hierarchy) is a different story since these are created before processing their content (files within). I supposed having such a config as `ignoreemptydir` would apply the same reasoning you mentioned above: after installing something, check if any directory/sub-directory is empty and delete it. I guess this would be much easier than processing each and every directory creation.

What about using a simple action like the following (applied to the dotfile for example, *untested*):
```yaml
actions:
  clearemptydir: find '{0}' -empty -type d -delete
dotfiles:
  d_awesome:
      dst: ~/.config/awesome
      src: config/awesome
      link: nolink
      ignoreempty: true
      instignore:
      - '*empty'
      actions:
      - clearemptydir "~/.config/awesome"
```
