### ISSUE TITLE
[feature] System config

### ISSUE THREAD

**Issue by sapristi** [deadc0de6/dotdrop#315]
Hello, and thank you for this awesome tool.

One idea that came to me for a way to handle system (root) configuration files is the following:

 - add a way to abort installing a config file. This could be done by parsing the result of a `pre` action, expecting  a custom return code, or a specific string in stdout.

This way, it would be possible to check that a certain condition is true before installing a file (e.g. current user uid is 0), in a very flexible way.

**Comment by deadc0de6** [comment]
This is already how it works.

```yaml
actions:
  pre:
    test-ret: "false"
dotfiles:
  f_test:
    src: test
    dst: ~/.test
    actions:
      - test-ret
 ```

Since the action returns a non zero code, then the dotfile is not installed
```bash
$ ./dotdrop.sh install
	-> executing "false"
[WARN] action returned code 1
[ERR] pre-action "test-ret" failed
[ERR] installing "f_test" failed: pre-action "test-ret" failed

0 dotfile(s) installed.
```
