### ISSUE TITLE
[help] Best way to deal with alternate files?

### ISSUE THREAD

**Issue by imchairmanm** [deadc0de6/dotdrop#328]
**What I am trying to achieve**

Hello, I'm trying to get a good understanding of the best practices surrounding providing alternate versions of files for different hosts.  For example, if my personal machine and my work machine both require an `~/.ssh/config` file, but they are completely different, what is the best way to configure the system to understand that difference, while handling updates, comparisons, and installations seemlessly?

**What I have tried so far**

Currently, I understand that I can manually adjust the configuration and filesystem to rename things to differentiate somewhat.  For instance, in my dotfiles directory, I can manually rename them `dotfiles/ssh/config.personal` and `dotfiles/ssh/config.work` and then treat them as completely separate files in the config:

```yaml
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
dotfiles:
  f_ssh_config_personal:
    src: ssh/config.personal
    dst: ~/.ssh/config
  f_ssh_config_work:
    src: ssh/config.work
    dst: ~/.ssh/config
profiles:
  personal:
    dotfiles:
    - f_ssh_config_personal
  work:
    dotfiles:
    - f_ssh_config_work
```

From here, installing works correctly using `dotdrop --profile=personal install`.  However, using update seems a bit trickier as it tries to update both `dotfiles/ssh/config.personal` and `dotfiles/ssh/config.personal` when I use `dotdrop --profile=personal update` for instance.  Is there a better way to make this play nicely so that it recognizes the two as completely separate files even though they link to the same source file in the home directory?

Really, just looking for ideas in case this is a solved problem.  I didn't see mention of this as I was looking through the docs, so I thought I'd ask.
