### ISSUE TITLE
[Feature request] Way to deactivate the banner

### ISSUE THREAD

**Issue by f-breidenstein** [deadc0de6/dotdrop#33]
Hi,

imho it would be great to have a way to deactivate the banner on every execution of the script. Especially at the beginning when you start to use dotdrop it's quite noisy ;)

Maybe just add a config flag which controls whether the banner gets drawn or not?

Best regards,
Felix

**Comment by deadc0de6** [comment]
I have added a switch `-b` or `--no-banner` to disable the banner. I thought it'd be more appropriate than a specific config entry in the config file.

**Comment by deadc0de6** [comment]
Also you can disable the banner through the config file by adding `banner: false` under the `config` entry with version 0.13:

```yaml
...
config:
  backup: true
  create: true
  dotpath: dotfiles
  banner: false
...
```
