### ISSUE TITLE
[bug] When Running Import Dotdrop Rewrites the Entire Yaml Config File Removing '---' and Empty lines

### ISSUE THREAD

**Issue by patbakdev** [deadc0de6/dotdrop#335]
Dotdrop version (and git commit if run from source): v1.8.0:4a0cf963acecb7de44e5fd1761c46d7cb5ac15c4
Using dotdrop as a submodule

**Describe the bug**

I have a yaml linter turned on by default and it always wants me to put the yaml marker ('---') at the top of the file. I also use empty lines to increase readability. When running import dotdrop rewrites the entire yaml config file removing the '---' and empty lines.

**Steps to Reproduce**

1. Create a dotfile with the following content:
```
---

config:
  backup: false
  banner: false
  create: true
  dotpath: .
  template_dotfile_default: false
  link_dotfile_default: nolink
  chmod_on_import: true

dotfiles:
  common-udev-usb:
    src: etc/udev/rules.d/95-usb.rules
    dst: /etc/udev/rules.d/95-usb.rules
    chmod: '644'

profiles:
  common:
    dotfiles:
      - common-udev-usb
```
2. Run `dotdrop import <some file>`
3. Open config file -> line at top is removed as well as all empty lines.
```
config:
  backup: false
  banner: false
  create: true
  dotpath: .
  template_dotfile_default: false
  link_dotfile_default: nolink
  chmod_on_import: true
dotfiles:
  common-udev-usb:
    src: etc/udev/rules.d/95-usb.rules
    dst: /etc/udev/rules.d/95-usb.rules
    chmod: '644'
  f_<some file>:
    src: ...
    dst: ...     
profiles:
  common:
    dotfiles:
      - common-udev-usb
      - f_<some file>
```
**Expected behavior**

Additional file is added to dotfiles and profiles sections without touching any other parts of the file.
