### ISSUE TITLE
[feature] Ability to use either relative or absolute symlinks in `link` option

### ISSUE THREAD

**Issue by RayZ0rr** [deadc0de6/dotdrop#348]
**A clear and concise description of what you want to happen.**

Add new values for the `link` option in the `config` value and `dotfiles` sections. The possible values can be:
* absolute :- Absolute symlink
* relative :- relative symlink
* link :- same as 'absolute' above for backward compatibilty
* nolink :- Copy
* link_children :- recursive (uses absolute)
```yaml
config:
 link_dotfile_default: (link|nolink|link_children|absolute|relative)
dotfiles:
  f_file1:
    src: file1
    dst: ~/tmp/test1
    link: (link|nolink|link_children|absolute|relative)
```

**Why**

Absolute symlinks are portable within the system. Relative symlinks are portable across different machines with different usernames.

**Additional info**

Possible reference links for corresponding functions:
1. https://docs.python.org/3/library/os.path.html#os.path.commonpath
2. https://stackoverflow.com/questions/7287996/get-relative-path-from-comparing-two-absolute-paths
3. https://stackoverflow.com/questions/21498939/how-to-circumvent-the-fallacy-of-pythons-os-path-commonprefix
4. https://www.geeksforgeeks.org/python-os-path-relpath-method/
