### ISSUE TITLE
[bug] Duplicate entries when using `import` feature in `profiles.dotfiles` section

### ISSUE THREAD

**Issue by RayZ0rr** [deadc0de6/dotdrop#349]
Dotdrop version (and git commit if run from source): v0.xxx
Using dotdrop: as a submodule, from pypi, '...'
Using from AUR
```sh
~$ dotdrop -v
1.8.2
(  1.8.2.r12.g30a0724-1 )
```

**Describe the bug**

When using the `imoprt` feature as mentioned here](https://dotdrop.readthedocs.io/en/latest/config-details/#profile-import-entry), duplicate entries are added to `profile  - dotfiles` section.

**Steps to Reproduce**

1. Extract the following tar `tar -xzf dotdroptest.tar.gz` in home folder : 
[dotdroptest.tar.gz](https://github.com/deadc0de6/dotdrop/files/8734961/dotdroptest.tar.gz)
    or create the following config files in `$HOME/dotdroptest`
`config.yaml`
```yaml
config:
  dotpath: dotfiles
dotfiles:
  f_test1:
    src: dotdroptest/test1
    dst: ~/dotdroptest/test1
  f_imported:
    src: dotdroptest/imported
    dst: ~/dotdroptest/imported
profiles:
  Arch:
    dotfiles:
    - f_test1
    import:
    - dotfiles.yaml
``` 

`dotfiles.yaml`
```yaml
dotfiles:
  - f_imported
```

2. Use the command in the dotdroptest folder `dotdrop -p Arch imported`
3. A new entry will be added to `config.yaml` . It will become
```yaml
config:
  dotpath: dotfiles
dotfiles:
  f_test1:
    src: dotdroptest/test1
    dst: ~/dotdroptest/test1
  f_imported:
    src: dotdroptest/imported
    dst: ~/dotdroptest/imported
profiles:
  Arch:
    dotfiles:
    - f_test1
    - f_imported
    import:
    - dotfiles.yaml
``` 

**Expected behavior**

Duplicate entries are not added.

**Comment by deadc0de6** [comment]
Thanks for reporting this however I was unable to reproduce the issue. 

What command are you running through `dotdrop -p Arch imported`? I tried with `import` and `update` but was able to reproduce. Can you double check and give me more info on which command triggers the bug.

Thanks!

**Comment by RayZ0rr** [comment]
Sorry, for lack of clarification. I will put detailed steps here again.

1. Extract the following tar `tar -xzf dotdroptest.tar.gz` in home folder : 
[dotdroptest.tar.gz](https://github.com/deadc0de6/dotdrop/files/8734961/dotdroptest.tar.gz)
2. Use the command in the `~/dotdroptest` folder `dotdrop -p Arch import imported`

`~/dotdroptest/config.yaml` before import command above:
```yaml
config:
  dotpath: dotfiles
dotfiles:
  f_test1:
    src: dotdroptest/test1
    dst: ~/dotdroptest/test1
  f_imported:
    src: dotdroptest/imported
    dst: ~/dotdroptest/imported
profiles:
  Arch:
    dotfiles:
    - f_test1
    import:
    - dotfiles.yaml
```
`~/dotdroptest/config.yaml` after import command:
```yaml
config:
  dotpath: dotfiles
dotfiles:
  f_test1:
    src: dotdroptest/test1
    dst: ~/dotdroptest/test1
  f_imported:
    src: dotdroptest/imported
    dst: ~/dotdroptest/imported
profiles:
  Arch:
    dotfiles:
    - f_test1
    - f_imported
    import:
    - dotfiles.yaml
```
