### ISSUE TITLE
Unexpected 'nolink' behavior with neovim and packer [help]

### ISSUE THREAD

**Issue by lyndhurst** [deadc0de6/dotdrop#354]
Hi,

I am just starting using dotdrop, and trying to get familiar with it before getting fancy with my configuration. So far everything has been working as I could expect from the documentation (backups, updates, installs and imports).

I have a simple configuration and I only imported my `nvim` configuration files. This means the `.config/nvim/init.lua` file, and my `.config/nvim/lua/config/` directory where I keep each plugin configuration in a separate file (even the `require("packer").startup` function in a `packer.lua` file).

```yaml
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_init.lua:
    src: config/nvim/init.lua
    dst: ~/.config/nvim/init.lua
  d_config:
    src: config/nvim/lua/config
    dst: ~/.config/nvim/lua/config
profiles:
  laptop:
    dotfiles:
    - f_init.lua
    - d_config
```

Since I am just starting to learn, I wanted to try out with `nolink` at first. I expected to have additional steps when tweaking my nvim config for changes to take effect like `dotdrop install` first and then some nvim reloading. But to my surprise that was not the case!

Changes made in the dotfiles repository take effect in nvim without doing a `dotdrop install`. Below are the steps to reproduce on my machine.

I edit my packer config file in the **dotfiles repo** using nvim, and I add a line like `use "akinsho/toggleterm.nvim"` I immediately do `PackerCompile`, then `PackerSync`, and the plugin gets installed.
 
I do a `dotdrop compare` and the diff confirms that the changes were not applied to the home folder. I do a `bat ~/.config/..../packer.lua` and the line added in the dotfiles `src` is not present there. I finally try `dotdrop install`, and the changes are mirrored to the home folder.

I tried the same kind of operations half a dozen times with consistent results, I am sorry for wasting your time if I missed something, but even after reading the doc, I feel that what I am describing is just not possible. I would greatly appreciate any help to understand what is happening.

Thank you for your time :)
