### ISSUE TITLE
[help] Skip adding to profile on import

### ISSUE THREAD

**Issue by mikelorant** [deadc0de6/dotdrop#360]
**What I am trying to achieve**
Import a dotfile without adding it to any profiles. This is useful because a profile can contain all defined dotfiles.

Example:
```
profiles:
  all:
    dotfiles:
    - ALL
```

**What I have tried so far**
Importing with `--profile=ALL`.

Is it possible to have the import command have a `--skip-profile` option?
