### ISSUE TITLE
snap dotdrop - bad symlinks

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#367]
I try to use snap dotdrop
With config 
```
  d_bin:
    dst: ~/.bin
    src: .bin
    link: link_children
```
and bad symlinks are created inside snap directory
`linked /home/niksfirefly/snap/dotdrop/44/.bin/notify to /home/niksfirefly/dotfiles/dotfiles/.bin/notify`

What I  am doing wrong?
Same setup as submodule works

**Comment by deadc0de6** [comment]
Can you try replacing `~` with the actual path of your home user: `/home/niksfirefly`:
```yaml
  d_bin:
    dst: /home/niksfirefly/.bin
    src: .bin
    link: link_children
```

To be honest I'm not sure exactly how snaps work but it uses some kind of [confinement](https://snapcraft.io/docs/snap-confinement). And it seems at least `$HOME` gets replaced with a path within the snap confinement. For example using `{{@@ env['HOME'] @@}}` ends up with the same issue you have.
Another workaround is to use `"/home/{{@@ env['USER'] @@}}/.bin"` which works though.

Dotdrop uses [os.path.expanduser](https://docs.python.org/3/library/os.path.html#os.path.expanduser) to replace `~` with the user home directory with the help of the `$HOME` environment variable unfortunately.
