### ISSUE TITLE
[help] Opt out of chmod/file-permission checks?

### ISSUE THREAD

**Issue by Lilja** [deadc0de6/dotdrop#369]
**What I am trying to achieve**
I just added a new dotfile that installs from my WSL image to my host machine. The config goes something like this:

```yaml
  wezterm_conf_wsl:
    src: wezterm
    dst: "/mnt/c/Users/Erik\ Lilja"
    link: "nolink"
```

When I run it, dotdrop tries to `chmod` the file to `755`. I don't like how dotdrop tries to change that, and I saw that you could put the desired chmod octal. But in this scenario, that octal could change and since its affecting a quite important directory I don't want it to perform any side effects.

**What I have tried so far**
put `chmod: 777` on that dotfile, but I think it's a shaky solution
