### ISSUE TITLE
Directory ignore pattern not working in upignore [bug] 

### ISSUE THREAD

**Issue by ask1234560** [deadc0de6/dotdrop#418]
Dotdrop version (and git commit if run from source): v1.14.0.r8.g9b62d57-1

**Describe the bug**
Ignore not working with directory in upignore 

Attaching the video.

https://github.com/deadc0de6/dotdrop/assets/25929911/20206407-2b55-4c0c-b80d-b2a05c0060a7

**Expected behavior**

`/home/ananthu/.config/dotfiles_bspwm/dotfiles/config/mpv/watch_later` should be ignored.

**Additional information**

The relevant part of the config file
```
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
    chmod: '700'
    cmpignore:
    - '*/watch_later'
    upignore:
    - '*/watch_later'
profiles:
  arch:
    dotfiles:
    - d_mpv

```

Dotdrop's execution with the debug logs (`--verbose`)
```bash
$ dotdrop update --verbose
```
Attaching the debug log.
[debug.log](https://github.com/deadc0de6/dotdrop/files/13327587/debug.log)

Thank you @deadc0de6 for dotdrop. If you need any other info please feel free to ask.

**Comment by deadc0de6** [comment]
Hello, Thanks for submitting this.
Could you try with `'*/watch_later/*`?

**Comment by deadc0de6** [comment]
@ask1234560 I was able to reproduce this and indeed it was *only* a problem of output as the directory is ignored but we still get an ouput saying it was *added*.

I'm working on a fix in [PR 419](https://github.com/deadc0de6/dotdrop/pull/419).

**Comment by ask1234560** [comment]
Hi @deadc0de6, thanks for working on the fix but i still face the issue.  

`dotdrop version - 1.14.0.r32.g4044dab-1`

1. 1st case

```
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
    chmod: '700'
    cmpignore:
    - '*/watch_later/*'
    upignore:
    - '*/watch_later/*'
profiles:
  arch:
    dotfiles:
    - d_mpv

```

Output -

![image](https://github.com/deadc0de6/dotdrop/assets/25929911/61a57a80-510c-4277-89cb-d8ef9f2f87e1)

Result - 
compare shows incorrect output

2. 2nd case
As per the current documentation for [ignoring directory](https://dotdrop.readthedocs.io/en/latest/config/config-file/#ignore-patterns)
```
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
    chmod: '700'
    cmpignore:
    - '*/watch_later'
    upignore:
    - '*/watch_later'
profiles:
  arch:
    dotfiles:
    - d_mpv

```

Output -
![image](https://github.com/deadc0de6/dotdrop/assets/25929911/c90b5622-f452-4117-ba0f-3b161009673f)

Result - 
compare works correctly, update breaks and adds the folder `watch_later` with the contents. 


I would be happy to provide any other info you need.
