### ISSUE TITLE
[bug] profile variables not merged on import_configs

### ISSUE THREAD

**Issue by marczz** [deadc0de6/dotdrop#423]
Dotdrop version last git  commit 4044dabd from 30/11/23 tagged 1.14.0, also tested with 1.12.9

When a configuration import a sub configuration and in the main and sub config there is a profile section which has a profile variable, even if the variable in both files are distinct. Dotdrop fail with "unable to merge"

I  created a simplified use case for this bug.

My main config file is
```
config:
  dotpath: dotfiles
  import_configs:
  - subconfig.yaml
dotfiles:
  f_test_config:
    dst: /tmp/test_config
    src: test_config
profiles:
  test:
    dotfiles:
    - f_test_config
    variables:
      onevar: "has some value"
```

The content of dotfiles is not relevant since it fails before using it.

The `subconfig` file is
```
config:
  dotpath: dotfiles
dotfiles:
  f_essai:
    src: essai.txt
    dst: /tmp/essai.txt
profiles:
  test:
    variables:
      somevar: "somevalue"
```

We should expect that the two config are merged, and the profile test has now the two variables `onevar`  and `somevar`.

But when I try, I get:
```
$dotdrop -c config_debug.yaml install -p test
[ERR] config error: unable to merge 
```

A full debug log is attached
[debug_log.txt](https://github.com/deadc0de6/dotdrop/files/13724496/debug_log.txt)
