### ISSUE TITLE
[bug] trailing new line seem to get removed when applying template

### ISSUE THREAD

**Issue by ShoHoukyo** [deadc0de6/dotdrop#438]
Dotdrop version (and git commit if run from source): v1.14.0
Using dotdrop: installed using Python 3.12.3, pipx 1.4.3-1, ubuntu-24.04

**Describe the bug**

 trailing new line seem to get removed when applying template

**Steps to Reproduce**

1. Create files as below
2. Run `DOTDROP_PROFILE=profile2_def dotdrop install`

**Expected behavior**

Generated file should be correct with correct new lines.

**Additional information**

config file (json is valid yaml)
```yaml
{
    "config": {
        "backup": true,
        "banner": true,
        "create": true,
        "dotpath": "template_files",
        "ignoreempty": false,
        "keepdot": false,
        "key_prefix": true,
        "link_dotfile_default": "nolink",
        "longkey": true,
        "showdiff": false
    },
    "dotfiles": {
        "common_f2": {
            "dst": "{{@@+ profile @@}}/common/f2",
            "src": "common/f2",
            "template": true
        }
    },
    "profiles": {
        "profile1abc": {
            "dotfiles": [
                "common_f2"
            ],
            "variables": {
                "var_RJC_pinotu___51e1db5e": "REJECT\n\toption output\t\t",
                "var____8dc4b111": "",
                "var____fbe9a844": "",
                "var__ifaRCpns_imf1__5c8ecb88": "\n\toption forward\t\tREJECT\n\toption masq\t\t1\n\toption mtu_fix\t\t1"
            }
        },
        "profile2_def": {
            "dotfiles": [
                "common_f2"
            ],
            "variables": {
                "var_RJC_pinotu___51e1db5e": "",
                "var____8dc4b111": "# ",
                "var____fbe9a844": "#",
                "var__ifaRCpns_imf1__5c8ecb88": ""
            }
        }
    }
}
```

Tempalte file f2:
```
config zone
	option name		wan
	{{@@+ var____8dc4b111 @@}}list   network		'wan'{%@@+ if profile == "profile1abc" @@%}{%@@+ elif profile == "profile2_def" @@%}
    option	network		'wan wan6'
	option input		DROP
	option output		ACCEPT
	option forward		DROP
	option masq		1
	option mtu_fix		1
    option log 1
    option log_limit '2/minute'
# option family 'ipv4'

#config zone
#	option name		wan6{%@@+ endif @@%}
#	list   network		'wan6'
{{@@+ var____fbe9a844 @@}}	option input		{{@@+ var_RJC_pinotu___51e1db5e @@}}ACCEPT{{@@+ var__ifaRCpns_imf1__5c8ecb88 @@}}
```

Expected file f2:
```
config zone
	option name		wan
	# list   network		'wan'
    option	network		'wan wan6'
	option input		DROP
	option output		ACCEPT
	option forward		DROP
	option masq		1
	option mtu_fix		1
    option log 1
    option log_limit '2/minute'
# option family 'ipv4'

#config zone
#	option name		wan6
#	list   network		'wan6'
#	option input		ACCEPT
```

Actual Result file `f2` (note the newline difference):
```
config zone
	option name		wan
	# list   network		'wan'    option	network		'wan wan6'
	option input		DROP
	option output		ACCEPT
	option forward		DROP
	option masq		1
	option mtu_fix		1
    option log 1
    option log_limit '2/minute'
# option family 'ipv4'

#config zone
#	option name		wan6#	list   network		'wan6'
#	option input		ACCEPT
```

Note:
https://github.com/deadc0de6/dotdrop/blob/7ee84a92ecdce09eec4fcafe47330e6788aa1ace/dotdrop/templategen.py#L58
It should work (but does not hence this bug) according to https://tedboy.github.io/jinja2/templ6.html
