### ISSUE TITLE
[help] dump/load Gnome's dconf settings

### ISSUE THREAD

**Issue by gmvelencoso** [deadc0de6/dotdrop#442]
**What I am trying to achieve**

(disclaimer: I achieved my goal, just wondering if it's the correct/best way)

Hey! I've just starting setting up dotdrop. Works great for dotfiles, but I had trouble managing Gnome's dconf.

I want to include dumps from Tilix terminal in my dotfiles repository. I struggled a bit TBH, but it seems to work now.

Now I plan to add other keys (or event the whole dconf DB), but I'd like to ask for advice on if this is the correct way.

**What I have tried so far**

I've defined an `action` and a `trans_update`.
```yaml
actions:
  dconf_load: dconf load "{0}" < "{{@@ _dotfile_abs_src @@}}"
trans_update:
  dconf_dump: dconf dump "{2}" > "{1}"
dconf_tilix:
    src: config/tilix/tilix.dconf
    dst: /tmp/tilix.dconf # a fake dst so dotdrop considers this to install.
    actions:
      - dconf_load /com/gexperts/Tilix/
    trans_update: dconf_dump /com/gexperts/Tilix/
    link: nolink
```

On `dotdrop install` it detects changes in the repository and executes the action, applying to dconf my new config.

On `dotdrop update`, it dumps whatever is in the dconf registry and if there's a diff with my `tmp/tilix.dconf` file, it will ask for confirmation:

```
Overwrite "/home/gerard/.dotfiles/dotfiles/config/tilix/tilix.dconf" with "/tmp/dotdrop-6n7sm47d/7043ac2a-d441-44dc-8a0b-b4965716d3c3"? [y/N] ? y
	-> "/home/gerard/.dotfiles/dotfiles/config/tilix/tilix.dconf" updated
``` 

> I can always delete the `/tmp` files to avoid the confirmation.

So, as said, I made it work, but I have the feeling this is not the right way.

Thanks in advance!
