### ISSUE TITLE
Feature request: config option to change default link

### ISSUE THREAD

**Issue by infokiller** [deadc0de6/dotdrop#49]
I'm using `link: true` almost always, so I would rather be able to set it once.

Thanks!

**Comment by deadc0de6** [comment]
`link` is to be set only when importing dotfiles and is by default set to `false` unless the switch `-l --link` is used on the command line when calling `import`.

Importing is usually used once for each files/directories and adding a `-l` to the command line allows to switch `link` to `true`. I'm not sure changing the default is a good idea though. How are you suggesting to improve it?

**Comment by infokiller** [comment]
I'm not suggesting to change the default but rather to have an option to change the default, for example:
```
config:
  link_by_default: true
dotfiles:
  d_config:
    dst: .config
    src: .config
    link: true
```

**Comment by deadc0de6** [comment]
Sure I can add that option. The `-l --link` would then be redundant in that case.
I'll see how to add this and will let you know.

**Comment by deadc0de6** [comment]
I have created the new option `link_by_default` in the config file in the branch `link_by_default` (af7ac510f15e3f84804c750497fcbda4883ace57). If the option is set to `true` any file imported will have the `link` key set to `true` even if `-l --link` is not provided when issuing `import`. 

Since the `link_by_default` option only applies to the import of dotfiles, dotdrop will still add the `link: true` key in the config file for each imported dotfile when that option set. 

For your example above resulting in 
```yaml
config:
  link_by_default: true
dotfiles:
  f_a:
    dst: .a
    src: a
    link: true
  f_b:
    dst: .b
    src: b
    link: true
```

Would that match what you need?
