### ISSUE TITLE
Feature: Action Argument(s)

### ISSUE THREAD

**Issue by weilbith** [deadc0de6/dotdrop#59]
Hey!
First thanks for this great tool with its awesome features.
I'd just found this here and being around to switch over. I like the idea to use this for installing the respective packages as well. So for example installing _NeoVim_ as `pre` action for the `nvim` dotfiles. This lead to a big bunch of actions when have to add so for each package with (a) dotfile(s). But most of them are pretty the same, cause just the package name changes. So for example if I'm working with _ArchLinux_ and like to install `nvim` and `nmutt` I do it this way:

```yaml
actions:
  pre:
    install_nvim: pacman -Sy neovim
    install_nmutt: pacman -Sy neomutt
...
dotfiles:
  f_nvim:
    actions:
      - install_nvim
    ...
  f_nmutt:
    actions:
      - install_nmutt
    ...
```

I think the "problem" is obvious. So what about the idea using arguments for actions. I'm not aware about the implementation but I imagine it in a way like this:

```yaml
actions:
  pre:
    install_package: pacman -Sy ${0}
...
dotfiles:
  f_nvim:
    actions:
      - install_package neovim
    ...
  f_nmutt:
    actions:
      - install_package neomutt
    ...
```

That would lead to a cleaner configuration and make changes easier cause of the single point of adjustment.
Thanks for listening!

**Comment by deadc0de6** [comment]
I like the idea! I'll see what I can do and come back to you.
Thanks for the suggestion!

**Comment by deadc0de6** [comment]
@weilbith I have a working version in the [parmaction](https://github.com/deadc0de6/dotdrop/tree/parmactions) branch.

It allows to provide parameter(s) to your actions as described in the [readme](https://github.com/deadc0de6/dotdrop/tree/parmactions#use-actions). For example:
```yaml
actions:
  echoaction: echo '{0}' > {1}
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
    actions:
      - echoaction "vim installed" /tmp/mydotdrop.log
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
    actions:
      - echoaction "xinitrc installed" /tmp/myotherlog.log
profiles:
  home:
    dotfiles:
    - f_vimrc
    - f_xinitrc
```
If you feel like it, give it a try and let me know what you think. Thanks!
If you have a more *interesting* example, let me know ;-)
