### ISSUE TITLE
Add option to programmatically find dst

### ISSUE THREAD

**Issue by Iambecomeroot** [deadc0de6/dotdrop#69]
Sometimes, programs used config folders that are different across systems. A good example of this is firefox. My firefox profile is stored under ~/.mozilla/firefox/r42yexow.default/`. Since I only have one firefox profile, I could easily find that id with a bash command. Is there any way to configure dotdrop to find that id?

**Comment by deadc0de6** [comment]
Currently it is not directly possible to use *dynamic* src or dst path for your dotfiles. This could be a nice improvements to dotdrop, I agree!

In the meantime, you can do this using actions and a temporary directory for example.

config.yaml
```yaml
actions:
  mozlink: ln -s ~/.firefox/somefile $(find ~/.mozilla/firefox -name '*.default')/somefile                                  
dotfiles:
  f_somefile:
    dst: ~/.firefox/somefile
    src: firefox/somefile
    actions:
      - mozlink
profiles:
  test:
    dotfiles:
    - f_somefile
```

The above config will install the dotfile `firefox/somefile` to a temporary file (in the example above into `~/.firefox/somefile`) and then the `mozlink` action will link that file back to the firefox profile directory with `ln -s ~/.firefox/somefile $(find ~/.mozilla/firefox -name '*.default')/somefile`.

Another solution would be to install the dotfile to a temporary directory and then move it to the mozilla profile directory (expecting that `/tmp` always exists on the filesystem and that the temporary filepath is unique):
```yaml
actions:
  mozlink: mv /tmp/.some_unique_path $(find ~/.mozilla/firefox -name '*.default')/somefile                                  
dotfiles:
  f_somefile:
    dst: /tmp/.some_unique_path
    src: firefox/somefile
    actions:
      - mozlink
profiles:
  test:
    dotfiles:
    - f_somefile
```
Could one of the above solve your issue?
