### ISSUE TITLE
support update transformations

### ISSUE THREAD

**Issue by abraverm** [deadc0de6/dotdrop#71]
Current transformation is one way (read) but it should support write too for update command. For example with GPG, transformation will able to decrypt and encrypt the file. In current state, update will overwrite the transformed file and require manual operations.

Configuration example:
```
f_my_secret_file:
  dst: ~/.my_secret_file
  src: my_secret_file.gpg
  trans:
  - gpg
  trans_write:
  - gpg
trans:
  gpg: gpg2 -d {0} > {1}
trans_write:
  gpg: gpg2 -e {0} -o {1}
```
