### ISSUE TITLE
listfiles should show managed directories files

### ISSUE THREAD

**Issue by abraverm** [deadc0de6/dotdrop#72]
Managed directories might have some files that are ignored, thus `listfiles` command should show what the actual files being managed in that directory instead of just showing destination from config file.

For example, managed folder `~/.my_app` has two files: config and my_app.log, the configuration will be:
```
dotfiles:
  d_my_app:
    dst: ~/.my_app
    src: my_app
    cmpignore:
    - '*.log'
```
Then `showfiles` command should show:
```
d_my_app (src: "my_app", link: False)
            -> ~/.my_app/config
```
Instead it shows:
```
d_my_app (src: "my_app", link: False)
            -> ~/.my_app
```
