### ISSUE TITLE
workdir should handle a relative path

### ISSUE THREAD

**Issue by Maelan** [deadc0de6/dotdrop#75]
Happy Christmas, and thanks for this handy software!

It seems that the _workdir_ option does not handle relative paths properly.

Steps to reproduce:

 0. Have dotdrop 0.24.0 (commit 0cb032f — latest at time of writing) installed under `~/dotfiles/`, with the sample `~/dotfiles/config.yaml` config file:
    ```yaml
    config:
      dotpath: templates
      workdir: generated
    dotfiles:
      f_test:
        dst: ~/test
        src: test
        link: true
    profiles:
      home:
        dotfiles:
        - f_test
    ```
    and this dotfile `~/dotfiles/templates/test`:
    
        {{@@ profile @@}}
    
    The intention is that we put our possibly templated dotfiles into `~/dotfiles/templates/`, while files generated from templates would go into `~/dotfiles/generated/`.
    
 0. Run:
    
        cd ~/dotfiles && ./dotdrop.sh --profile=home install f_test
    
 0. Observe:
    
        cat ~/dotfiles/generated/test
    
    shows the expected contents `home`; but:
    
        ls -l ~/test
    
    shows that the created symlink is wrong:

        lrwxrwxrwx 1 me users 14 Dec 26 23:12 /home/me/test -> generated/test
    
    The symlink points to the nonsensical relative path `generated/test`, instead of the intended absolute path `~/dotfiles/generated/test`.

As a point of comparison, when `~/dotfiles/templates/test` is not a template (ie. when it contains no jinja2 macro), then `~/test` is correctly symlinked to `~/dotfiles/templates/test`.

I think that having option _workdir_ accept a relative path (just as _dotpath_ does, relative to the config file) would be nice, precisely for the use case shown above. Even otherwise, producing nonsensical symlinks is a bug that should be fixed.
