### ISSUE TITLE
[Feature request] Allow per profile variables

### ISSUE THREAD

**Issue by mchwalisz** [deadc0de6/dotdrop#81]
I think it would be beneficial to allow variables in profiles as well. That would give much more power to templating engine.

Take a look at following example:

```
config:
  backup: true
  create: true
  dotpath: ~/.dotfiles/
  ignoreempty: false
  keepdot: false
  longkey: true
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
variables:
  git_email: home@email.com
profiles:
  work_host:
    dotfiles:
    - f_gitconfig
    variables:
      git_email: work@email.com
  private_host:
    dotfiles:
    - f_gitconfig
```
And the following git config:
```
[user]
    name = My Name
    email = {{@@ git_email @@}}
```
Now, while installing the `f_gitconfig`, dotdrop will merge the global and profile variables and put it to jinja2. Profile variables should have higher priority, so that work_host will have work email configured and all other will have the home email.

I would also consider dynvariables having the same functionality for completeness. I agree they are already dependent on the host but one could force different command to be executed per profile. Not sure here.
