### ISSUE TITLE
Feature Request - Action Requirements

### ISSUE THREAD

**Issue by weilbith** [deadc0de6/dotdrop#83]
Hey!
I must say it again, but great work what you have done here. I just came back after a while since I've time now and my private hacky scripts are not acceptable anymore.
But I tend to have the opinion that dotfiles are useless without their tool using them. So I always add an action to install a package with `pacman`, `pip`, `yarn`... (remember #59).  It would be awesome to make this `install` process even more "stable". Therefore pip must be secured to be installed before using it. I categorize my dotfiles in `profiles` (maybe not what they are meant for) and rarely install `ALL`. I don't know which profile depends on which package manager, cause a tool for a dotfile needs to be installed. So I would prefer to not manually install the required tools in advance. Of cause I could write some awkward `actions` like

```yaml
actions:
  pre:
    pip_install: test -n trizen -Qs pip || trizen -S python-pip; pip install {0}
    yarn_install: test -n trizen -Qs yarn || trizen -S yarn; yarn global add {0}
```

Even here I have now the problem that `trizen` must be available, which would lead to a much larger snake of commands, which repeats itself over and over (I choose `trizen` here even if the packages are available at default `pacman`, just to show the case).

What I would prefer is something like this:

```yaml
actions:
  trizen_install:
    command: trizen -S {0}
    requirement: trizen_itself_available

  requirements:
    trizen_itself_available:
      check: command -v trizen>/dev/null
      fail:  cd /tmp; git clone https://aur.archlinux.org/trizen.git; cd trizen; makepkg -si

    trizen_package_available:
      check: trizen -Qs {0}
      requirement: trizen_itself_available
      fail: trizen_install {0}

   pre:
     pip_install:
       command: pip install {0}
       requirement: trizen_package_available python-pip

    yarn_install:
      command: yarn global add {0}
      requirement: trizen_package_available yarn
```

Here `actions` can be not a _String_ only, but also an _Object_. The property `command` is the same to execute like for _String_ only `actions`. The additional `requirement` property can refer to `actions` of the `requirements` section (sibling of `pre` and `post` `actions`). They must be handled before the action's `command` gets executed. These are completely new and must define a `check` and `fail` property. First is the command to verify if the requirement is met. The second will be executed to if the check has failed. A possibly useful implemention would be to rerun the check afterwards to make sure this command has resolved it and throw an error if not.
Additionally `requirments` could define a `requirement` reference by there own, which are necessary to run the `check` command.

Same could be useful for `trans` definitions where most-likely `gpg` is required.

What are your thoughts about such an idea. For me it would be absolutely awesome and make it becoming **the** dotfile manager.

**Comment by weilbith** [comment]
I registered that I mixed up the `fail` property to be a shell command and a `action` reference. I guess both are quite useful. But to be able to differ between them, a distinction must be found. A possible solution would be to have two property names instead of one (e.g. `fail_command` and `fail_action`). Not sure if this is the best one, since now we need a priorization in case both are defined.

Also I'm not even sure if `action` arguments could be handover. I used some bash like syntax for functions.

**Comment by deadc0de6** [comment]
Wow I like the idea! What about adding dynamic/interpreted variables to actions (like for [the dotfile paths](https://github.com/deadc0de6/dotdrop#dynamic-dotfile-paths))?

Your example would then look something like that:
```yaml
dynvariables:
  trizen_itself_available: (command -v trizen>/dev/null || cd /tmp; git clone https://aur.archlinux.org/trizen.git; cd trizen; makepkg -si)
  trizen_package_install: {{@@ trizen_itself_available @@}} && trizen -S --needed

actions:
  trizen_install: {{@@ trizen_package_install @@}} {0}
  pre:
    pip_install: {{@@ trizen_package_install @@}} python-pip && pip install {0}
    yarn_install: {{@@ trizen_package_install @@}} yarn && yarn global add {0}
```

**Comment by weilbith** [comment]
Incredible how this `dynvariables` could be used. I'm a bit disappointed that I haven't found this myself. To be honest my view of these object was different. Feels like abusing them. :stuck_out_tongue_winking_eye:
This solution is maybe not thaaat chic, but I guess my proposal was way too big with a lot of overhead. Especially if it is already possible with existing features (is it already?).
I will give it a try very soon!

Besides: Can I abuse any other feature even more to call actions without a relation to a dotfile entry, but within/for a profile? :thinking:

**Comment by deadc0de6** [comment]
This isn't already in (variable substitution in actions) but shouldn't be too difficult to implement, I'll have a look this week-end.

Regarding your other features, this is possible, please open an issue so we can discuss it.

**Comment by deadc0de6** [comment]
I have implemented recursive variables (see [available variables](https://github.com/deadc0de6/dotdrop#available-variables)) and dynamic actions (see [Use actions](https://github.com/deadc0de6/dotdrop#use-actions)).

Can you give it a try and let me know what you think?

**Comment by weilbith** [comment]
Hmm. I have this small example:
```yaml
dynvariables:
  trizen_itself_available_test: (command -v trizen_not_there>/dev/null || echo 'not available')

actions:
  pre:
    trizen_install_package_test: {{@@ trizen_itself_available_test @@}} && echo "{0}"
```

What I get is this error:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/thore/dotfiles/dotdrop/dotdrop/dotdrop.py", line 535, in <module>
    if main():
  File "/home/thore/dotfiles/dotdrop/dotdrop/dotdrop.py", line 433, in main
    conf = Cfg(os.path.expanduser(args['--cfg']))
  File "/home/thore/dotfiles/dotdrop/dotdrop/config.py", line 118, in __init__
    if not self._load_file():
  File "/home/thore/dotfiles/dotdrop/dotdrop/config.py", line 140, in _load_file
    self.content = yaml.load(f)
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/parser.py", line 540, in parse_flow_mapping_first_key
    return self.parse_flow_mapping_key(first=True)
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/parser.py", line 543, in parse_flow_mapping_key
    if not self.check_token(FlowMappingEndToken):
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/thore/.local/lib/python3.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '@' that cannot start any token
```

As stupid test, I tried this version:
```yaml
actions:
  pre:
    trizen_install_package_test: echo "{{@@ trizen_itself_available_test @@}}" && echo "{0}"
```
And therefore I get the `dynvariable` executed in a sub-shell as it looks like and its output is printed.

**Comment by weilbith** [comment]
Moreover I don't get your example for the docs.
1. Where do you use the `action` `trizen_install`.
2. The `dynvariable` named `trizen_package_install` does not use the `{0}` parameter, right?

**Comment by deadc0de6** [comment]
Your issue is probably due to the fact that variables need to be enclosed in quotes (this is due to jinja2). 
Try with something like that:
```yaml
dynvariables:
  trizen_itself_available_test: "(command -v trizen_not_there>/dev/null || echo 'not available')"

actions:
  pre:
    trizen_install_package_test: "{{@@ trizen_itself_available_test @@}} && echo {0}"
```

I'll update the doc.

BTW it makes little sense to use `{{@@ trizen_itself_available_test @@}} && ...` since the variable `trizen_itself_available_test` will always be true.

Regarding my example, it was just trying to show how to transform your examples with variables. Those actions (`trizen_install`, `yarn_install`, `pip_install`) would be used by some dotfile, for example:

```yaml
dynvariables:
  trizen_itself_available: (command -v trizen>/dev/null || cd /tmp; git clone https://aur.archlinux.org/trizen.git; cd trizen; makepkg -si)
  trizen_package_install: {{@@ trizen_itself_available @@}} && trizen -S --needed
actions:
  trizen_install: {{@@ trizen_package_install @@}} {0}
  pre:
    pip_install: {{@@ trizen_package_install @@}} python-pip && pip install {0}
    yarn_install: {{@@ trizen_package_install @@}} yarn && yarn global add {0}
dotfiles:
  d_vim
    dst: ~/.vim
    src: vim
    actions:
      - trizen_install "vim"
```

**Comment by weilbith** [comment]
I'am confused by what you are saying related to your examples. :see_no_evil: 
In your examples your are not using quotation marks. That's why I haven't used them (haven't used jinja2 before, in case this is related).
Of cause I'm using the `action` for a dotfile. :grin: 
Even copy your corrected (?) snippet above does not work.
But got my mistake: `dynvariables` are false here. They are parsed before and their output is replaced everywhere, instead of executed each time where referenced. They lead to errors, because if they contain some commands to execute, but without any output or new command the follow up will fail. (e.g. `; command...` fails, if before `;` is no command to chain). Moreover this could also lead to a false outcome, since I wanted to install `trizen` for example only, if one dotfile for the selected profile requires it. In case I would rewrite a `dynvariable` to make sure `trizen` is available in forehand and refer it at any place to make it getting parsed (does it need to be referenced to get executed?!), this would be a different outcome.
What I want is reusable code snippets. Therefore I use `variables`. And this is working:
```yaml
variables:
  trizen_itself_available_test: (command -v trizen_not_there>/dev/null || echo 'not available')

actions:
  pre:
    trizen_install_package_test: "{{@@ trizen_itself_available_test @@}}; echo {0}"
```

Is it necessary to require quotation marks on every place I use a `dyn`-/`variable`?
And moreover I registered, that the output of `dotdrop install` prints the whole command. This is nice, but I guess it would be useful to prefix it with the name of the `action` with its arguments, since these should be meaningful and better to read. Is this arguable?

Thanks a lot for your great help and kindliness! :+1:

**Comment by deadc0de6** [comment]
I'm sorry, I just tried to create an example similar to what you had as a demo but I haven't tested it, my bad. It added to the confusion, I'm sorry. The idea was just to show the possibility, not a working examples. You are right, my example was wrong as `variables` are to be used and not `dynvariables`.

Here's a working example:
```yaml
dotfiles:
  f_test:
    dst: ~/.test
    src: test
    actions:
      - cookie_mv_somewhere "/tmp/moved-cookie"
profiles:
  slim:
    dotfiles:
    - f_test
variables:
  cookie_dir_available: (test -d /tmp/cookiedir || mkdir -p /tmp/cookiedir)
  cookie_header: "{{@@ cookie_dir_available @@}} && echo 'header' > /tmp/cookiedir/cookie"
  cookie_mv: "{{@@ cookie_header @@}} && mv /tmp/cookiedir/cookie"
actions:
  cookie_mv_somewhere: "{{@@ cookie_mv @@}} {0}"
```

The error we saw above (the `found character '@' that cannot start any token`) comes from the yaml parser unable to parse `@` chars. It is therefore needed to quote strings in the config file that have special chars (like the `@`). It is also a good practice to quote the rest too (if they contain variable substitution, to avoid bad surprise with jinja2).

Here's an example for `trizen` that works:
```yaml
dotfiles:
  f_test:
    dst: ~/.test
    src: test
    actions:
      - trizen_install "vim"
variables:
  trizen_exists: (hash trizen 2>/dev/null || (rm -rf /tmp/trizen; git clone https://aur.archlinux.org/trizen.git /tmp/trizen && cd /tmp/trizen && makepkg -si))                                                                                                         
  trizen_package_install: "{{@@ trizen_exists @@}} && trizen -S --needed"
actions:
  trizen_install: "{{@@ trizen_package_install @@}} {0}"
```

I would suggest you have a look at [this page](https://github.com/deadc0de6/dotdrop/wiki/global-config-files) on managing system and user files with dotdrop (since you are somehow trying to install packages that need some elevated privileges like `makepkg`).

The issue with the `dynvariables` being executed twice was a bug, I have fixed it, thanks a lot for catching that! It should be fixed now. Remember that `dynvariables` are being resolved even if the dotfiles is not installed as opposed to `actions` where those are only applied when the dotfiles is installed. `dynvariables` are not linked to a dotfiles per se and should be used as *information getters* like:
```yaml
dynvariables:
  mozpath: find ~/.mozilla/firefox -name '*.default'
```

I have also fixed the information displayed with `--verbose` for actions and now you get the key and the arguments.

I hope all these information help. Thanks again for your help!
