### ISSUE TITLE
Should actions come before checks?

### ISSUE THREAD

**Issue by Iambecomeroot** [deadc0de6/dotdrop#84]
Hello again @deadc0de6! Sorry to be bothering you again so soon. My problem right now is that I am trying to install [`Prezto`](https://github.com/sorin-ionescu/prezto) with a pre action and then overwrite `~/.zprezto/runcoms/zpreztorc` with a symlink to my dotfile. My `config.yaml` is as follows.
```yml
actions:
  pre:
    prezto-install: test -e ~/.zprezto/init.sh || (rm -rf ~/.zprezto && zsh $HOME/.dotfiles/zprezto/zprezto-install)
config:
  backup: true
  create: true
  dotpath: .
  workdir: ~/.config/dotdrop
dotfiles:
  f_zpreztorc:
    dst: ~/.zprezto/runcoms/zpreztorc
    src: ./zprezto/zpreztorc
    link: true
    actions:
      - prezto-install
```

The problem is that the check [here](https://github.com/deadc0de6/dotdrop/blob/c8d549d837ff8af76fa141315ef2451ccc8f0323/dotdrop/installer.py#L153) (and the prompt to overwrite) happens before there is anything to overwrite, as the actions were not yet run. My proposition is to run pre actions before installing. This presents obvious problems, as rejecting the prompt to overwrite after actions were run can have side effects. Maybe the checks should happens twice, before and after actions? What do you think? I hope I am not looking over something obvious.

My temporary workaround is to install `zpreztorc` to `/tmp` and to use a post script to symlink with `--force`. However, this kind of defeats the purpose of `dotdrop` is everything is done with bash commands.

**Comment by deadc0de6** [comment]
I added an additional check after the *pre* action is executed.

I tested it with following config
```yaml
actions:
  pre:
    pre-install: test -e ~/.test/cookie || mkdir -p ~/.test; touch ~/.test/cookie; echo 'from install' > ~/.test/testfile
dotfiles:
  d_test:
    dst: ~/.test/testfile
    src: test/testfile
    link: true
    actions:
      - pre-install
```

Can you give it a try and let me know if that solve your issue?
