### ISSUE TITLE
dotdrop.linktypes.LinkTypes in yaml

### ISSUE THREAD

**Issue by mchwalisz** [deadc0de6/dotdrop#88]
I have noticed the following `yaml` tags started to creep into my dotdrop config. I'm using dotdrop from master branch.

```yaml
  f_config_albert_albert.conf:
    dst: ~/.config/albert/albert.conf
    link: !!python/object/apply:dotdrop.linktypes.LinkTypes
    - 1
    src: config/albert/albert.conf
```

This also reminds me about `pyyaml` [warning](https://pyyaml.org/wiki/PyYAMLDocumentation):

> Warning: It is not safe to call yaml.load with any data received from an untrusted source! yaml.load is as powerful as pickle.load and so may call any Python function. Check the yaml.safe_load function though.

and wanted to ask how is yaml managed by dotdrop.

**Comment by deadc0de6** [comment]
Thanks for reporting this. It seems this is bug introduced by PR #77. I've fixed it.
I have also changed calls to `load` with `safe_load`, thanks for pointing that out!

It has been fixed in the master branch and I'll release a new version soon on pypi.

**Comment by deadc0de6** [comment]
New version 0.25.2 is released on pypi (https://pypi.org/project/dotdrop/) and the aur version will be updated soon.
Thanks again for your help!

**Comment by deadc0de6** [comment]
To fix it in your config, you can simply replace the weird python code with `true` or `false`:
```yaml
  f_config_albert_albert.conf:
    dst: ~/.config/albert/albert.conf
    link: !!python/object/apply:dotdrop.linktypes.LinkTypes
    - 1
    src: config/albert/albert.conf
```
to
```yaml
  f_config_albert_albert.conf:
    dst: ~/.config/albert/albert.conf
    link: true
    src: config/albert/albert.conf
```

Sorry for that.
