### ISSUE TITLE
user based dotfiles?

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#89]
I assume there is no way to add specific dotfiles to profiles based on username right?
I try simple hack with dynvariable substition but it not works
[WARN] unknown included profile "uid_{{@@ d_uid @@}}"
   
```
dynvariables:
- d_uid: id --user

include:
- "uid_{{@@ d_uid @@}}"
```

Is there a chance to apply dynvariables substitution for profiles/includes?

**Comment by mchwalisz** [comment]
The [readme](https://github.com/deadc0de6/dotdrop#dynamic-dotfile-paths) gives you an example on how to use the dynamic variables.

I don't think that the `key` of the dotfile should be made variable. You can easily set either source or destination paths as variables.

**Comment by niksfirefly** [comment]
Well I think you missed the point
I want to create profiles
uid_0
uid_1000
and then include one of them automatically for host profile based on user uid 
so it is problem with value interpolation not key:
```
include:
- "uid_{{@@ d_uid @@}}"
```

**Comment by deadc0de6** [comment]
Thanks for suggesting this. 

I have implemented dynamic include (allowing the use of `variables` and `dynvariables`).

You should be able to do something like that:
```yaml
variables:
  var1: "john"
dynvariables:
  d_user: "echo $USER"
profiles:
  profile_john:
    dotfiles:
    - f_john_dotfile
  profile_bill:
    dotfiles:
    - f_bill_dotfile
  p1:
    include:
    - "profile_{{@@ d_user @@}}"
  p2:
    include:
    - "profile_{{@@ var1 @@}}"
```

It is available in the *dyninclude* branch, can you give it a try?

See also the doc: <https://github.com/deadc0de6/dotdrop/tree/dyninclude#include-dotfiles-from-another-profile>

**Comment by deadc0de6** [comment]
BTW If you try to install dotfiles for root (uid 0), you might want to give a quick read to [this wiki page](https://github.com/deadc0de6/dotdrop/wiki/global-config-files).

**Comment by niksfirefly** [comment]
Wow that was fast :) :+1: 
I'll give it a try
I wonder is there another better/simpler solution to this problem user@host-profile ?
For example
Nobody? use root account with X so for same host I must exclude i3 config for root or include for X users

**Comment by deadc0de6** [comment]
I'm not sure to understand your question, could you elaborate?

**Comment by niksfirefly** [comment]
I assume that dotfiles must be used/modified per user
dotdrop use only host as profile name
I know dotdrop profile option on CLI, I was thinking about more automatic solution.

**Comment by deadc0de6** [comment]
The profile can be specified in different ways:

* per default it gets the hostname of the host it runs on
* there's the `-p --profile` cli switch
* the environment variable `DOTDROP_PROFILE` can be used to specify the profile

Regarding the config, you could specify which config file to load using the `-c --cfg` cli switch (it defaults to `config.yaml`).

If you want to have dotdrop use a different profile for a specific user, you could potentially export the variable `DOTDROP_PROFILE` from your shell config file (`.bashrc` or `.zshrc` for example).

There are currently no other ways of specifying the config file than using the `-c --cfg` cli switch however I could implement a variable (like for example `DOTDROP_CONFIG`) that would work like the `DOTDROP_PROFILE` variables. Would that help?

**Comment by deadc0de6** [comment]
Or maybe I misunderstood your question ... 

In dotdrop, a dotfile is stored only once, and gets dynamically generated based on the profile. 

For example:
```bash
#!/bin/bash

# load Xresources
userresources=$HOME/.Xresources
if [ -f "$userresources" ]; then
      xrdb -merge "$userresources" &
fi

# launch the wm
{%@@ if profile == "home" @@%}
exec awesome
{%@@ elif profile == "office" @@%}
exec bspwm
{%@@ endif @@%}
```

Have look at the following resources on how dotdrop works:
* <https://github.com/deadc0de6/dotdrop#example>
* <https://github.com/deadc0de6/dotdrop/issues/26#issuecomment-378488616>
* <https://deadc0de.re/articles/dotfiles.html>

**Comment by niksfirefly** [comment]
Ok I understand your point and IMHO dotdrop docs are written really good,so this is not criticism
but with multiple OSes / hosts /users and dotfiles config yaml become scary and big :)

What do you think about splitting or moving profiles out of config.yaml to files based
on OS/host/user|group/name|uid hierarchy:

OS.host.user.uid.yaml
host.user.yaml
group.yaml
host.yaml
... etc.

those files could go to config.d directory and could be completly optional like in yadm solution
https://yadm.io/docs/alternates

BTW I also like @mchwalisz feature request #90 

regards

**Comment by deadc0de6** [comment]
Hm that's an interesting suggestion. I could implement a way of externalizing the profile dotfiles.

It will make the config file less scary and shorter but it would make the management a bit more difficult since one would have to jump across multiple files to manage all the settings.

For example:

`config.yaml`
```yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_tmux:
    dst: ~/.tmux.conf
    src: tmux.conf
profiles:
  home:
    from_file: config.d/home.yaml
  office:
    from_file: config.d/office.yaml
  vps:
    dotfiles:
    - f_vimrc
```

`config.d/home.yaml`
```yaml
dotfiles:
- f_xinitrc
```

`config.d/office.yaml`
```yaml
dotfiles:
- f_vimrc
- f_tmux
```

What do you think?

**Comment by deadc0de6** [comment]
It might be quite good to *gather* dotfiles related to one solution in a global profile, like for example:

`config.d/openbox.yaml`
```yaml
dotfiles:
  - f_autostart
  - f_environment
  - f_menu.xml
  - f_rc.xml
```

`config.yaml`
```yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_tmux:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_autostart:                                                                                                                   
    dst: ~/.config/openbox/autostart
    src: config/openbox/autostart
  f_environment:
    dst: ~/.config/openbox/environment
    src: config/openbox/environment
  f_menu.xml:
    dst: ~/.config/openbox/menu.xml
    src: config/openbox/menu.xml
  f_rc.xml:                                                                                                                      
    dst: ~/.config/openbox/rc.xml
    src: config/openbox/rc.xml
profiles:
  home:
    from_file: 
    - config.d/openbox.yaml
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - f_tmux
```

**Comment by niksfirefly** [comment]
Sure It could be nice addition :) 
but my intention was also to put more automatism and convention to configs based on dynamic data (from running OS) when dotfiles are installed.
I guess you can simply gather OS info/architecture/username and if the file exist apply automatic config 
For example
If we use openbox on Ubuntu as user niksfirefly and below files exists

```
config.d/Ubuntu.openbox.niksfirefly.yaml
config.d/Ubuntu.yaml
config.d/niksfirefly.yaml

```
concat options from those files and apply with main config.yaml file.
This way we may also use less jinja template IF-ELSE statements

**Comment by deadc0de6** [comment]
I see your point. To be honest I prefer the explicit than the implicit. 

But what you are trying to do is already doable with dotdrop, there are multiple ways to do that.

---

1) let's say you have a profile defined per hostname and per user (for example `bill_home`, `bill_office` and `john_home`)
```yaml
profiles:
  bill_home:
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - f_tmux
  john_home:
    include:
    - bill_home
  bill_office:
    dotfiles:
    - f_vimrc
```

You could easily construct the profile name using environment variable with for example
```
export DOTDROP_PROFILE="${USER}_${hostname}"
```

---
2) Or you could directly include profiles using environment variables based only on the hostname (what is the current default for the profile):
```yaml
profiles:
  bill_home:
    dotfiles:
    - f_xinitrc
  john_home:
    dotfiles:
    - f_vimrc
  home:
    include:
    - "{{@@ env['USER'] @@}}_home"
```

3) You could also use dynamic variables to include specific profiles
```yaml
dynvariables:
  user: "echo $USER"
  host: "[ $HOST = somehostname ] && echo home || echo office"
profiles:
  bill_home:
    dotfiles:
    - f_tmux
  john_home:
    dotfiles:
    - f_vimrc
  bill_office:
    dotfiles:
    - f_test
  john_office:
    dotfiles:
    - f_xinitrc
  myhostname:
    include:
    - "{{@@ user @@}}_{{@@ host @@}}"
```

4) Moreover If I add the externalization of profiles through files, you could even do something like this:
```yaml
profiles:
  home:
    from_file: "config.d/{{@@ env['USER'] @@}}_{{@@ profile @@}}.yaml"
```

with two files (`config.d/bill_home.yaml` and `config.d/john_home.yaml`) containing the different dotfiles per profile.

Does any of the above match your use-case?

**Comment by deadc0de6** [comment]
FYI I have merged the *dyninclude* branch into master.

**Comment by niksfirefly** [comment]
Of course thank you :)
Call me lazy :) when I suggest 
config.d/Ubuntu.openbox.niksfirefly.yaml

I see another pros - when I use Ubuntu and browse someone repos with dotdrop dropfiles with config.d
```
Centos.yaml
Ubuntu.yaml 
```
can spare me some time because I am interested in Ubuntu (possibly with openbox or i3).
That optional implicit config.d - regardless simple onefile config.yaml - could direct people to some standard.

This could also lead to some default interesting collections with tweaks for specific releases
OS / X-managers etc. 
but maybe this is overengineering :)

regards

**Comment by deadc0de6** [comment]
I see already a few ways to *group* and *parameterize* the dotfiles. I could add the loading of profiles from an external file as shown above with the `from_file` if that'd be useful for you.

Or would you be ready to do a PR as an attempt to implement this?

**Comment by niksfirefly** [comment]
from_file is better than nothing please do and thank you :)
I am some sort of a Ruby guy so I cant help with python for now :(
regards
PS. Last small suggestion from me - You can move optional/extras solutions from main docs to wiki to improve readability for beginners.

**Comment by deadc0de6** [comment]
I made an attempt at importing profile dotfiles from an external file in the [extdotfiles](https://github.com/deadc0de6/dotdrop/tree/extdotfiles) branch.

It should allow to do something like this:

`config.yaml`
```yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_abc:
    dst: ~/.abc
    src: abc
  f_def:
    dst: ~/.def
    src: def
  f_xyz:
    dst: ~/.xyz
    src: xyz
profiles:
  p1:
    dotfiles:
    - f_abc
    import:
    - somedotfiles.yaml
```

`somedotfiles.yaml`
```yaml
dotfiles:
  - f_def
  - f_xyz
```

Could you give it a try and let me know if you find any issue?
