### ISSUE TITLE
Recursive include not working

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#91]
I dont know - is it intentional?
```
profiles:
  host:
    include:
    - user
  common:
    dotfiles:
    - d_ssh
  user:
    dotfiles:
    - d_i3
    include:
    - common
```

d_ssh is not installed for profile host
