### ISSUE TITLE
Feature request :   variables in import_variables

### ISSUE THREAD

**Issue by Eluminae** [deadc0de6/dotdrop#99]
Hello there !
I'd like to request a little feat. It would be to be able to :
```
  import_variables:
    - colors/{{@@ color_theme @@}}.yaml
```
It do not work currently so I guess we canno't use variable else where than `import`

Do you think this is possible ?

TY by advance, dotdrop rocks !
Reed

**Comment by deadc0de6** [comment]
Thanks!
Yes that's possible, I have implemented *dynamic* variable imports.
It is currently only available in the master branch but will release a new version on pypi soon.

**Comment by deadc0de6** [comment]
new version released!

**Comment by Eluminae** [comment]
I got a problem ! Profile variables are not used in the import_variable. Is it normal ? :)

```
config:
  import_variables:
    - colors/{{@@ color_theme @@}}.yaml
profiles:
  laptop-home:
    variables:
      color_theme: hybrid
  laptop-work:
    variables:
      color_theme: solarized-dark
variables:
  color_theme: solarized
```

Something like this can't be done?
